### ISSUE TITLE
plugin crashes when using for_each

### ISSUE THREAD

**Issue by vdmkenny** [scaleway/terraform-provider-scaleway#1030]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.3

### Affected Resource(s)
Potentially all, I encountered this with
* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_server" "k8s" {
  for_each = {
    1 = "fr-par-1"
    2 = "fr-par-2"
  }
  name = "kube-${each.key}"
  type = "DEV1-S"
  image = "rockylinux_8"
  project_id = var.project_id
  zone = each.value

  tags = [var.environment]

  private_network {
    pn_id = scaleway_vpc_private_network.internal.id
  }
}

```

### Debug Output

https://gist.github.com/vdmkenny/417b750f8a2faec97d7279cb32212c53

### Expected Behavior

Terraform should create 2 instances of the server using the `for_each` metakey.

### Actual Behavior

Terraform created these instances, but then got into this error-state during the next refresh

### Steps to Reproduce

Create multiple server instances like I did with the `for_each` metakey

**Comment by Monitob** [comment]
Hello maybe you can try something like this

 ```resource "scaleway_instance_server" "main" {
	provider = scaleway.pdev
	for_each = {
		"fr-par-1" = scaleway_vpc_private_network.pn01.id
		"fr-par-2" = scaleway_vpc_private_network.pn02.id
	}
  name =  format("kube-%s", each.key)
  type = "DEV1-S"
  image = "rockylinux_8"
  project_id = var.project_id
  zone = each.key

  tags = [var.environment]

  private_network {
    pn_id = each.value
  }
}```

Feel free to do further questions by our [slack-terraform]: https://scaleway-community.slack.com/app_redirect?channel=terraform
