### ISSUE TITLE
Don't make the instance type change disruptive

### ISSUE THREAD

**Issue by deimosfr** [scaleway/terraform-provider-scaleway#1037]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to figure out how to update node types from Terraform config without downtime. By default, it completely shut down all the nodes and create new ones. Of course, it's not expected when running production pods on the cluster.

This is why I'm trying to find a solution. I've tested several things on AWS EKS and lifecycles like:
```
  lifecycle {
    create_before_destroy = true
  }
```
Unfortunately, I'm getting this error on Scaleway:
```
Error: scaleway-sdk-go: invalid argument(s): name does not respect constraint, pool name must be unique across the cluster
```

I've also tried upgrade_policy as well on a cluster of 5 nodes:
```
  upgrade_policy {
    max_unavailable = 4
  }
```

Unfortunately, it deletes everything before creating new nodes. Is there a way to manage this automatically via Terraform?

Otherwise, the only thing I see is a 2 step way:
1. creating a new pool with the desired size
2. deleting the old pool once it's done
This is just not user-friendly and I would like the Scaleway provider to handle it properly like EKS.

Here is an example to bootstrap workers to reproduce:
```
resource "scaleway_k8s_pool" "kubernetes_cluster_workers_1" {
  cluster_id    = scaleway_k8s_cluster.kubernetes_cluster.id
  name          = "${var.kubernetes_cluster_id}_1"
  node_type     = "dev1-l"

  region        = var.region
  zone          = var.zone

  # use Scaleway built-in cluster autoscaler
  autoscaling         = true
  autohealing         = true
  size                = "5"
  min_size            = "5"
  max_size            = "10"
  wait_for_pool_ready = true
}
```

Once deployed, if you try to change the node type, it will completely delete all nodes and create new ones, leading to pod downtime.

Thanks in advance

### New or Affected Resource(s)

Kubernetes Kapsule

### Potential Terraform Configuration

```
  lifecycle {
    create_before_destroy = true
  }
```

**Comment by jtherin** [comment]
Have you tried to also change pool name at the same time ?

**Comment by deimosfr** [comment]
No I did not, just changed the type

**Comment by jtherin** [comment]
With create_before_destroy = true, terraform try to create a second pool with the same name.

But two pools can't have the same name at the same time (which does not occurs when creating after deleting) :
`Error: scaleway-sdk-go: invalid argument(s): name does not respect constraint, pool name must be unique across the cluster`

So by editing instance type AND the name, will create a new pool with another name, which should not trigger the error constraint.

**Comment by deimosfr** [comment]
You're right @jtherin . Is there a way to let Terraform manage the automatically name?

In fact I was expecting the same behavior than EKS. I can handle it, but just let me know if there are some plans to randomize it on change, provider side.

It would save me some time. Thanks in advance

**Comment by remyleone** [comment]
I think we can document in a guide a way to migrate from one pool type to the next without downtime.
