### ISSUE TITLE
[scaleway_apple_silicon_server] bad region format

### ISSUE THREAD

**Issue by rdavison** [scaleway/terraform-provider-scaleway#1039]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.1.3

### Affected Resource(s)

* scaleway_apple_silicon_server

### Terraform Configuration Files

```hcl
provider "scaleway" {
  project_id      = "REDACTED"
  region          = "fr-par"
  zone            = "fr-par-1"
}

resource "scaleway_apple_silicon_server" "myserver" {
  name = "myserver"
  type = "M1-M"
}
```

### Debug Output

I cannot generate it now because my account only has a quota of 1 for apple silicon server, and I cannot delete the server for 24 hours.

### Expected Behavior

The scaleway_apple_silicon_server should have been created.

### Actual Behavior

```
scaleway_account_ssh_key.account_ssh_key: Creating...
scaleway_account_ssh_key.account_ssh_key: Creation complete after 0s [id=REDACTED]
scaleway_apple_silicon_server.myserver Creating...
scaleway_apple_silicon_server.myserver Still creating... [10s elapsed]
scaleway_apple_silicon_server.myserver Still creating... [20s elapsed]
scaleway_apple_silicon_server.myserver Still creating... [30s elapsed]
scaleway_apple_silicon_server.myserver Still creating... [40s elapsed]
╷
│ Error: scaleway-sdk-go: bad region format, available regions are: fr-par, nl-ams, pl-waw
│
│   with scaleway_apple_silicon_server.myserver,
│   on appleserver.tf line 1, in resource "scaleway_apple_silicon_server" "myserver":
│    1: resource "scaleway_apple_silicon_server" "myserver" {
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

It appears that the error only happens after a create request has been sent and succeeds. While Scaleway is busy creating the server, Terraform is polling to check the status, and that's where it appears to be failing. My suspicion is that the API server is not sending a valid `region` value when terraform polls for the status, and the scaleway go client is failing here: https://github.com/scaleway/scaleway-sdk-go/blob/master/scw/locality.go#L190

**Comment by remyleone** [comment]
Hello, is the apple silicon server successfully created? Does terraform recognize it if so? If you have trouble could you try to import it in the terraform state? It seems rather strange because apple silicon is not a region product but a zoned product.
