### ISSUE TITLE
Add Region to scaleway_lb_ip

### ISSUE THREAD

**Issue by sgendrot** [scaleway/terraform-provider-scaleway#1049]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, in the scaleway_lb_ip, we can’t specify a region, it use the provider region. We work on several regions and we have to create a provider for every region to create the lb_ip in the good region.

### New or Affected Resource(s)

* scaleway_lb_ip

### Potential Terraform Configuration

```hcl
resource "scaleway_lb_ip" "ip" {
    region = "nl-ams"
}
```

**Comment by remyleone** [comment]
@sgendrot lb are zoned could you try to use a `zone = nl-ams-1` and see if it works for you?
