### ISSUE TITLE
Resource to emit a new API pair key

### ISSUE THREAD

**Issue by Nainterceptor** [scaleway/terraform-provider-scaleway#1052]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a devOps engineer, I've a root terraform project (in gitlab), where I create via terraform some other gitlab projects, that are owned by dev teams (Basically, I have rights on root gitlab project, teams have rights on sub gitlab projects). On these projects, teams are able to create merge requests to tune their infrastructure (quota, deploy a DB...).
I want to add security, by generating a new API key pair, (access et secret keys), project by project, then inject it in gitlab variables (or maybe in Vault, or anywhere else). In this way, I'm able to limit issue of token leak via a team member with maintainer rights.

### New or Affected Resource(s)

* scaleway_keys ?

**Comment by remyleone** [comment]
This is handled by [resource_iam_api_key](https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_iam_api_key.go) It will be soon released once IAM reaches beta status.
