### ISSUE TITLE
Panic: index out of range with rdb_privilege

### ISSUE THREAD

**Issue by bLuka** [scaleway/terraform-provider-scaleway#1054]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

`Terraform v1.1.2`

### Affected Resource(s)

* `scaleway_rdb_privilege`

### Terraform Configuration Files

I don't think this would be meaningful. It looks to be tied to an unexpected or not properly handled API response.

### Panic Output

[See here](https://gist.github.com/bLuka/10882f2e3263185bc987e1fa46c3c966).

### Expected Behavior

I expected to see the Terraform plan, as it always shown to me.

### Actual Behavior

Terraform panics on the Scaleway provider, even though I did not modify anything related to scaleway_rdb_privilege after the last working plan.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

I have 2 rdb instances created on that project. Both have 2 users. Instance A has 1 admin, and 1 user **with no privilege**, while instance B has 1 admin, and 1 user with 2 privileges.

### References

It is related to this line: [scaleway/resource_rdb_privilege.go#L120](https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_rdb_privilege.go#L120).

A quick fix would be to check the array's length before dereferencing, but what to do if array is empty? Error handling?

[API documentation here](https://developers.scaleway.com/en/products/rdb/api/#privileges-13f20d) don't mention 404 if no privileges are found ([as it is checked in the code here](https://github.com/scaleway/terraform-provider-scaleway/blob/0b4d02388f8dd161684428533125cd01b3f6d506/scaleway/resource_rdb_privilege.go#L113)). So I'm wondering if this would do the trick:

```go
	if err != nil {
		if is404Error(err) { // Can API really throw 404 on this?
			d.SetId("")
			return nil
		}
		return diag.FromErr(err)
	}
	// Additional check here:
	if len(res.Privileges) == 0 { // (Or res.TotalCount I think?)
		d.SetId("")
		return nil // Are we ok with that too?
	}

	var privilege = res.Privileges[0]
	// …
```

Hope that'd be useful!

Kind regards

**Comment by bLuka** [comment]
Hello,

I tried to get a workaround by removing resources from Scaleway (didn't fix), and then removing rdb_* from Terraform's state. It did the trick, and recreated the resources after applying, but then, next `terraform plan` failed again.

As this is blocking, I'll try debugging it on my side. I never touched Terraform providers development, so any hint or docs would be appreciated!

**Comment by Monitob** [comment]
Hello, Thank you for the ticket. We have to do a fix on the database API for this. Even though I can do a workaround to make it work and unblock you. I'm on it.
