### ISSUE TITLE
Error: cant parse localized id when importing scaleway_lb_frontend

### ISSUE THREAD

**Issue by altuhovsu** [scaleway/terraform-provider-scaleway#1101]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/scaleway/scaleway v2.2.1-rc.1

### Affected Resource(s)

* scaleway_lb_frontend

### Terraform Configuration Files

```hcl
resource "scaleway_lb_frontend" "lbfrontend" {
  for_each = var.lb_frontends
  lb_id        = scaleway_lb.mainlb.id
  backend_id   = scaleway_lb_backend.lbbackend[each.value.backendname].id
  name             = each.key
  inbound_port = each.value.inbound_port
}
```

### Debug Output

```hcl
2022-02-19T15:15:48.375+0200 [ERROR] vertex "import scaleway_lb_frontend.lbfrontend[\"test2\"] result" error: cant parse localized id:
2022-02-19T15:15:48.375+0200 [ERROR] vertex "scaleway_lb_frontend.lbfrontend[\"test2\"] (import id \"fr-par-1/c6c2b300-4dce-4be4-bd1b-c80768eafa90\")" error: cant parse localized id:
╷
│ Error: cant parse localized id: 
│ 
│ 
╵

2022-02-19T15:15:48.378+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
```

### Expected Behavior

Resource sucessfuly imported to the state

### Actual Behavior

Resource is not importing. Error is appear:

Error: cant parse localized id: 

### Steps to Reproduce

1. `terraform import 'scaleway_lb_frontend.lbfrontend["test"]' fr-par-1/c6c2b300-4dce-4be4-bd1b-c80768eafa90`

**Comment by remyleone** [comment]
Hello @altuhovsu could you update your ticket with the minimal snippet of code that reproduces the issue? We would like to add it to our test suite to ensure there is no regression.

**Comment by altuhovsu** [comment]
@Monitob @remyleone Thank you! Minimal code also do not works
```
terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
      version = "2.2.1-rc.1"
    }
  }
  required_version = ">= 0.13"
}

provider "scaleway" {
  zone       = "fr-par-1"
  region     = "fr-par"
}

resource "scaleway_lb_frontend" "lbfrontend01" {

}
```
execution:
```
terraform import scaleway_lb_frontend.lbfrontend01 fr-par-1/c6c2b300-4dce-4be4-bd1b-c80768eafa90
scaleway_lb_frontend.lbfrontend01: Importing from ID "fr-par-1/c6c2b300-4dce-4be4-bd1b-c80768eafa90"...
scaleway_lb_frontend.lbfrontend01: Import prepared!
  Prepared scaleway_lb_frontend for import
scaleway_lb_frontend.lbfrontend01: Refreshing state... [id=fr-par-1/c6c2b300-4dce-4be4-bd1b-c80768eafa90]
╷
│ Error: cant parse localized id: 
│ 
│ 
╵
```
