### ISSUE TITLE
Support Containers As a Service

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#1138]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for [Containers as a Service](https://www.scaleway.com/en/docs/faq/serverless-containers/)

### New or Affected Resource(s)

* scaleway_resource_container
* scaleway_resource_container_cron
* scaleway_resource_container_namespace
* scaleway_datasource_container
* scaleway_datasource_container_cron
* scaleway_datasource_container_namespace

### Potential Terraform Configuration

```hcl
resource scaleway_registry_namespace main {
  name = "my-registry-name"
  description = "registry namespace for container as a service"
  is_public = true
}

resource scaleway_container_namespace main {
  name = "my-container-ns-name"
  description = "container"
}

resource scaleway_container main {
  name = "my-container"
  description = "my description"
  namespace_id = scaleway_container_namespace.main.id
  registry_image = "${scaleway_registry_namespace.main.endpoint}/alpine:test"
  port = 9997
  cpu_limit = 140
  memory_limit = 256
  min_scale = 3
  max_scale = 5
  timeout = 600
  max_concurrency = 80
  privacy = "private"
  protocol = "h2c"
  redeploy = true

  environment_variables = {
	  "foo" = "var"
  }
}
```

### References

* #1103
* #1128

- [x] scaleway_resource_container
- [x] scaleway_resource_container_cron
- [x] scaleway_resource_container_namespace
- [x] scaleway_datasource_container
- [x] scaleway_datasource_container_cron
- [x] scaleway_datasource_container_namespace
- [x] documentation

**Comment by paretl** [comment]
Hey! Thanks for the amazing work, I'm currently using it a lot to deploy automatically the containers from Gitlab runners
I just have a question for you (I didn't want to create an issue for that)

Is that a possibility, in the future, to update a container by using the same Docker tag, with the Terraform module ?
For example, I've deployed a `toto:dev` container and I would like to update it with my new image of `toto:dev` by applying one more time the Terraform scripts

Maybe you will advice to me to use more the version tags to update the container, you will be right. 
I just need to know for my future usage :smile: 

Thanks in advance!

**Comment by Monitob** [comment]
Thank you for the feedback I'm going to explore adding a new attribute hash like [functions](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/function#zip_hash)

**Comment by Monitob** [comment]
@paretl Thanks for the feedback. This option will be soon available. Please check #1415 for more details.
