### ISSUE TITLE
Empty kubeconfig on aliased data.scaleway_k8s_cluster when SCW_SECRET_KEY and SCW_ACCESS_KEY are used

### ISSUE THREAD

**Issue by Nainterceptor** [scaleway/terraform-provider-scaleway#1181]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```sh
❯ terraform -v  
Terraform v1.1.7
on darwin_arm64
+ provider registry.terraform.io/scaleway/scaleway v2.2.0
```

### Affected Resource(s)

* data scaleway_k8s_cluster

(I've not tested other data source)

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "~> 2.2.0"
    }
  }
  required_version = ">= 1.0"
}

variable "scaleway_cluster_development_project_id" {
  type = string
}
variable "scaleway_cluster_development_access_key" {
  type = string
}
variable "scaleway_cluster_development_secret_key" {
  type = string
}
variable "scaleway_cluster_development_cluster_id" {
  type = string
}
variable "scaleway_cluster_production_project_id" {
  type = string
}
variable "scaleway_cluster_production_access_key" {
  type = string
}
variable "scaleway_cluster_production_secret_key" {
  type = string
}
variable "scaleway_cluster_production_cluster_id" {
  type = string
}

provider "scaleway" {
  alias      = "scaleway_development"
  region     = "fr-par"
  zone       = "fr-par-1"
  access_key = var.scaleway_cluster_development_access_key
  secret_key = var.scaleway_cluster_development_secret_key
  project_id = var.scaleway_cluster_development_project_id
}

provider "scaleway" {
  alias      = "scaleway_production"
  region     = "fr-par"
  zone       = "fr-par-1"
  access_key = var.scaleway_cluster_production_access_key
  secret_key = var.scaleway_cluster_production_secret_key
  project_id = var.scaleway_cluster_production_project_id
}

data "scaleway_k8s_cluster" "prod" {
  provider   = scaleway.scaleway_production
  cluster_id = var.scaleway_cluster_production_cluster_id
}

data "scaleway_k8s_cluster" "dev" {
  provider   = scaleway.scaleway_development
  cluster_id = var.scaleway_cluster_development_cluster_id
}

resource "null_resource" "dev" {
  triggers = {
    token_dev = data.scaleway_k8s_cluster.dev.kubeconfig[0].token
    token_prod = data.scaleway_k8s_cluster.prod.kubeconfig[0].token
  }
}
```

### Debug Output

https://gist.github.com/Nainterceptor/f8c0e1dc932e2e6bbeb32bb7620fde01

### Expected Behavior

When we use two times the provider, to target 2 connexion account, then use alias, each data/resources will use the provider from the parameter. With or without environment variables.

### Actual Behavior

When SCW_SECRET_KEY and SCW_ACCESS_KEY are set (with valid values), `data.scaleway_k8s_cluster` return an empty kubeconfig

### Steps to Reproduce

1. `terraform plan` with only variables filled, it's working
2. `export SCW_SECRET_KEY=<redacted, valid secret from ~/.scw/config.yaml>`
3. `export SCW_ACCESS_KEY=<redacted, valid access key from ~/.scw/config.yaml>`
4. `terraform plan` with variables filled, it's not longer working, but output the panic output working

### Important Factoids

Nothing related to our account

**Comment by Codelax** [comment]
Env variables override provider profile, profile override order can be seen here https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/provider.go#L285
