### ISSUE TITLE
scaleway_vpc_public_gateway_dhcp_reservation does not update the ip

### ISSUE THREAD

**Issue by jannishuebl** [scaleway/terraform-provider-scaleway#1185]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v1.1.7
on linux_amd64

### Affected Resource(s)

* scaleway_vpc_public_gateway_dhcp_reservation

### Expected Behavior

When ip or mac is changed it should update the resource in scaleway

### Actual Behavior

The update is not working

### Steps to Reproduce

1. create a scaleway_vpc_public_gateway_dhcp_reservation
2. change the ip 
3. apply the change

* #0000

**Comment by remyleone** [comment]
Hello, could you paste a snippet of code that reproduces the behavior you observe?

**Comment by jannishuebl** [comment]
I thanks for fixing, IP changes are working now but the mac does not work for me. (seems that delete+create is necessary at least its in the ui console)

**Comment by remyleone** [comment]
Hello @jannishuebl could you open a new issue with a minimal snippet of code that reproduces the MAC address problem you are experiencing? It would help us fix it for the next release :)
