### ISSUE TITLE
Instances in private network never obtain dynamic IP with 2.2.1-rc2

### ISSUE THREAD

**Issue by gaeldb** [scaleway/terraform-provider-scaleway#1200]
Hi team,

From 2.2.1-rc1, instances provisionned in a private network never obtain a dynamic DHCP release.
I don't explicity declare `scaleway_vpc_public_gateway_dhcp_reservation` in order to kept fully automated DHCP attribution.
Works perfectly with 2.2.0.
Note: private network and DHCP are managed from Scaleway console, not from Terraform.

### Terraform Version

```
Terraform v1.1.7
on linux_amd64
```

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl

data "scaleway_vpc_private_network" "pvn" {
  name    = "pvn"
}

resource "scaleway_instance_server" "instance1" {
  type       = "DEV1-S"
  image      = "debian_bullseye"
  name       = "instance1"
  private_network {
    pn_id = data.scaleway_vpc_private_network.pvn.id
  }
}
```

### Actual Behavior

With 2.2.1-rc2, instance1 never obtains dynamic IP from DHCP (nothing in API or Scaleway console)
With 2.2.0, instance1 obtains dynamic IP from DHCP.

**Comment by Monitob** [comment]
Thanks for report this. It will be fixed in our new tag.
