### ISSUE TITLE
destroy a scaleway_container_namespace

### ISSUE THREAD

**Issue by elielhaouzi** [scaleway/terraform-provider-scaleway#1215]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/scaleway/scaleway v2.2.1-rc.3

### Affected Resource(s)

scaleway_container_namespace and maybe scaleway_registry_namespace

### Terraform Configuration Files

```hcl
resource "scaleway_container_namespace" "prod" {
  name   = "name"
  region = "fr-par" # For the moment, we can create a container namespace only in Paris
}
```

### Expected Behavior

On apply, it creates a container namespace AND a namespace in the Container Registry.
On destroy, it destroys the namespace in the containers and in the Container Registry

### Actual Behavior

It destroy the namespace only in the Containers without destroying the namespace in the container registry.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by SkYNewZ** [comment]
What do you think about an optional argument that specifies if we want to destroy the related registry on namespace deletion ? Like the `google_project_service`'s `disable_on_destroy` one.  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/google_project_service#disable_on_destroy

**Comment by remyleone** [comment]
#959
