### ISSUE TITLE
Fail `terraform plan` if server image is invalid

### ISSUE THREAD

**Issue by abitrolly** [scaleway/terraform-provider-scaleway#123]
```
✗ terraform version
Terraform v0.11.13
+ provider.scaleway v1.9.2
```

Creating resource with invalid image id fails to `apply`, while `plan` is successfull.
```
resource "scaleway_server" "xe3" {
  name = "xe3"

  # https://community.scaleway.com/t/list-of-image-uuids-without-api/7672/2
  image = "Ubuntu_Bionic"
  type  = "ARM64-2GB"
}
```
```
$ terraform plan
...
Terraform will perform the following actions:

  + scaleway_server.xe3
      id:           <computed>
      boot_type:    <computed>
      cloudinit:    <computed>
      enable_ipv6:  "false"
      image:        "Ubuntu_Bionic"
      name:         "xe3"
      private_ip:   <computed>
      public_ip:    <computed>
      public_ipv6:  <computed>
      state:        <computed>
      state_detail: <computed>
      type:         "ARM64-2GB"
...
$ terraform apply
...
Error: Error applying plan:

1 error(s) occurred:

* scaleway_server.xe3: 1 error(s) occurred:

* scaleway_server.xe3: StatusCode: 400, Type: invalid_request_error, APIMessage: Validation Error, Details: map[image:[Ubuntu_Bionic is not a valid UUID.] volumes:[required key not provided]]
...
```
### Expected result
Fail during `terraform plan`.

**Comment by abitrolly** [comment]
Ideally it could detect mismatched `region` and `arch`.

**Comment by marco-m** [comment]
Hello @QuentinBrosse @jerome-quere any chance to have a look at this (valid) bug? Merci :-)

**Comment by QuentinBrosse** [comment]
Hi @marco-m,

We will try to implement a validation of the image (UUID or label) at the `plan` stage.
As `scaleway_server` is deprecated, only the new `scaleway_instance_server` resource will be concerned.

**Comment by marco-m** [comment]
Hello @QuentinBrosse, merci! (and I agree that it makes sense to focus only on `scaleway_instance_server`).

**Comment by remyleone** [comment]
Hello, I'm not sure how to perform this check in an efficient manner. I think this step should be performed in the read function of the resource. The problem is: that we would need to perform this check (and therefore perform an API call) every time regardless of whether we are in "plan" mode or not. That seems inefficient. 

I'm open to reconsider but if to implement this check we have to perform an API call to see if the image and arch are well-matched then it does not seem to be worthwhile. Especially because it would fail anyway in the create step.

**Comment by remyleone** [comment]
There is currently no clear support in the SDK to perform this cache. Therefore it would have to be created and maintained which is an extra cost for a very limited benefit. I would reconsider my position if it was something natively supported by the terraform SDK.

**Comment by abitrolly** [comment]
@remyleone I don't see what's wrong with API call during plan execution. If `terraform` has to do a lot of API calls to know the current state. I am almost sure relying on fail during the `create` step is an anti-pattern, when the same error can be caught durin `plan`, but I would be interested to read the discussion that proves otherwise.

**Comment by remyleone** [comment]
Maybe the solution could be to use a validatefunc #1121

**Comment by Codelax** [comment]
The correct way to do so would be by using instance_image data source.
Using data sources is the solution to have api requests during plan.

```
data scaleway_instance_image ubuntu {
  name = "Ubuntu_focal"
}

resource "scaleway_instance_server" "server" {
  image = data.scaleway_instance_image.ubuntu
  type  = "PRO2-XXS"
}
```
