### ISSUE TITLE
update loadbalacer certificate not working

### ISSUE THREAD

**Issue by jannishuebl** [scaleway/terraform-provider-scaleway#1249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

current master

### Affected Resource(s)

* scaleway_lb_certificate

### Terraform Configuration Files
first: 

```hcl
 "scaleway_lb_certificate": {
      "cert01": {
        "lb_id": "${scaleway_lb.main.id}",
        "name": "cert1",
        "letsencrypt": {
          "common_name": "infra.xxxx",
          "subject_alternative_name": [
            "www.infra.xxxx"
          ]
        }
      }
    }
```

changed to: 

```hcl
 "scaleway_lb_certificate": {
      "cert01": {
        "lb_id": "${scaleway_lb.main.id}",
        "name": "cert1",
        "letsencrypt": {
          "common_name": "infra.xxxx",
          "subject_alternative_name": [
            "www.infra.xxxx",
            "xxx.infra.xxx",
          ]
        }
      }
    }
```

### Expected Behavior

I would expect that the new subdomain is added to the certificate or a new one is generated and replaced

### Actual Behavior

the certificate is unchanged

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by remyleone** [comment]
Hello and thanks for sending us this bug report. It is impossible to update in place a certificate to include new alternative names in place. You would need to delete and recreate a new certificate to make it happen. I've opened #1275 to automate it when alternative names are updated.

**Comment by jannishuebl** [comment]
Hi @remyleone,

thanks, it now tries to recreate the certificate. 

i just tried to test this fix. but i still having a problem: 

when i applying it first tries to delete the certificate, which leads to the following error: 

caleway_lb_certificate.cert01: Destroying... [id=fr-par-1/*****]
scaleway_lb_backend.bkd_content: Creating...
cloudflare_record.content_infra: Creating...
scaleway_lb_backend.bkd_content: Creation complete after 1s [id=fr-par-1/*****]
cloudflare_record.content_infra: Creation complete after 2s [id=******]
╷
│ Error: scaleway-sdk-go: http error 400 Bad Request: operation was rejected because the certificate is used on a frontend

**Comment by remyleone** [comment]
Yes, I think it is safer to proceed in the way you describe. Do not hesitate to open a new issue with a minimal code snippet if you encounter a problem.
