### ISSUE TITLE
Public gateway DHCP `pool_high` is read as `pool_low`

### ISSUE THREAD

**Issue by Timost** [scaleway/terraform-provider-scaleway#1295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_vpc_public_gateway_dhcp

It's pretty obvious here: https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_vpc_public_gateway_dhcp.go#L232

`pool_high` is read from the `pool_high` value.

### Actual Behavior

`pool_high` is read  from the `pool_low` value.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This  creates unnecessary changes in `terraform apply` but doesn't actually break anything.

**Comment by remyleone** [comment]
Thanks :) it is fixed now :)

**Comment by Timost** [comment]
🙏 👍
