### ISSUE TITLE
VPC Gateway DHCP: `push_default_route` always true

### ISSUE THREAD

**Issue by karelorigin** [scaleway/terraform-provider-scaleway#1315]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.2.1

### Affected Resource(s)

* scaleway_vpc_public_gateway_dhcp

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = "2.2.1"
    }
  }
}

provider "scaleway" {
  access_key = var.scw_access_key
  secret_key = var.scw_secret_key
  project_id = var.scw_project_id
  region     = var.scw_region
  zone       = var.scw_zone
}

resource "scaleway_instance_server" "test" {
  count = 2

  type              = "DEV1-S"
  image             = "ubuntu_focal"
  enable_dynamic_ip = true

  private_network {
    pn_id = scaleway_vpc_private_network.pn01.id
  }
}

resource "scaleway_vpc_private_network" "pn01" {
  name = "pn_test_network"
}

resource "scaleway_vpc_public_gateway_ip" "gw01" {
  # No configuration necessary
}

resource "scaleway_vpc_public_gateway_dhcp" "dhcp01" {
  subnet             = "192.168.1.0/24"
  push_default_route = false
}

resource "scaleway_vpc_public_gateway" "pg01" {
  name  = "foobar"
  type  = "VPC-GW-S"
  ip_id = scaleway_vpc_public_gateway_ip.gw01.id
}

resource "scaleway_vpc_gateway_network" "main" {
  gateway_id         = scaleway_vpc_public_gateway.pg01.id
  private_network_id = scaleway_vpc_private_network.pn01.id
  dhcp_id            = scaleway_vpc_public_gateway_dhcp.dhcp01.id
  cleanup_dhcp       = true
  enable_masquerade  = true
}
```

### Expected Behavior

The public gateway should not be set as the default route for connected instances:

![image](https://user-images.githubusercontent.com/20503272/171857066-e4395bf3-ab20-4779-8df0-3b194a696d00.png)

### Actual Behavior

The gateway was set as the default route for connected instances

![image](https://user-images.githubusercontent.com/20503272/171857186-16cb66d5-d195-44f7-8d99-8d3159f98326.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by Codelax** [comment]
Thanks for your issue, this is fixed by #1316. This should make its way into the next release.
