### ISSUE TITLE
Private IPs as scaleway_k8s_pool attributes

### ISSUE THREAD

**Issue by ilyarubinchik** [scaleway/terraform-provider-scaleway#1327]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello!

scaleway_k8s_pool resource is returning `nodes` attribute, which contains public_ip of the node, but not private ip.
Thus we need to do something like this, if we want to further use private IPs (for instance to deploy LoadBalancer):
```hcl
locals {
  nodes_private_ips = [for node in data.scaleway_instance_server.pool : node["private_ip"]]
}

data "scaleway_instance_server" "pool" {
  for_each = toset([for node in scaleway_k8s_pool.pool.nodes : node["name"]])
  name = each.value
}
``` 

This code works if applied to pre-created cluster, but not works from scratch, because for_each is undefined until apply, and terraform raises error:
```
│   on kostyl/outputs.tf line 9, in data "scaleway_instance_server" "pg-pool":
│    9:   for_each = toset([for node in scaleway_k8s_pool.pool.nodes : node["name"]])
│     ├────────────────
│     │ var.cluster.size is 3
│     │ var.nodes is a list of object, known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.
```

I think nodes private IPs could be returned by `scaleway_k8s_pool`, to make things a lot easier and convenient.

Thanks!

New attribute in scaleway_k8s_pool resource, containg private IPs of nodes in the pool.

* range scaleway_k8s_pool.pool.nodes -> node["private_ip"]

**Comment by remyleone** [comment]
@jtherin do you think you could add the private_ip attributes to the k8s API?

**Comment by remyleone** [comment]
We talked about @jtherin about the evolution of the networking part of the nodes within a pool. Private networks in Kubernetes cluster will soon be available and we are going to deprecate even the public IP part and migrate entirely to secure private network management of Kubernetes connectivity. Therefore it does not seem worthwhile to add support for a private IP because they will be deprecated anyway in some months. This replacement will bring new features and more integration with the rest of the Scaleway products.

**Comment by BabisK** [comment]
@remyleone Has there been any progress on this? It would be nice to get the private IP addresses of the nodes in a pool. But I don't see that information in the [Node endpoint of the API](https://www.scaleway.com/en/developers/api/kubernetes/#path-nodes-get-a-node-in-a-cluster) yet. But I see that PublicIPv4 is deprecated. What is this supposed to be replaced by?

**Comment by jtherin** [comment]
you can use kubernetes_nodes datasource to obtain InternalIP and ExternalIP of a node.
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/data-sources/nodes#addresses
