### ISSUE TITLE
Function Endpoints / Custom Domain

### ISSUE THREAD

**Issue by rawkode** [scaleway/terraform-provider-scaleway#1349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would like the ability to add endpoints to my functions to support custom domains

### New or Affected Resource(s)

* scaleway_function

### Potential Terraform Configuration

```hcl
resource scaleway_function main {
  namespace_id = scaleway_function_namespace.main.id
  runtime      = "go118"
  handler      = "Handle"
  privacy      = "private"
  endpoints = [
    "mycustomdomain.com"
  ]
}
```

### References

* #980 is closed, but there's still checkboxes left open

**Comment by Finkes** [comment]
Does this issue also cover custom domains for serverless containers?

**Comment by Codelax** [comment]
@Finkes  This issue does not cover for serverless containers but I created one. Both should be included in next release
