### ISSUE TITLE
Scaleway instance does not boot correctly when deployed

### ISSUE THREAD

**Issue by elghali97** [scaleway/terraform-provider-scaleway#1384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.2.4
on windows_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/scaleway/scaleway v2.2.3

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_security_group" "scaleway_instance_sg" {
  name                    = "fr-sg-test-instance"
  description             = "Allow TLS inbound traffic"
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  inbound_rule {
    action = "accept"
    port   = "22"
  }

  inbound_rule {
    action = "accept"
    port   = "80"
  }

  inbound_rule {
    action = "accept"
    port   = "443"
  }
}

resource "scaleway_instance_volume" "additional_volume" {
  size_in_gb = 20
  type = "l_ssd"
}

resource "scaleway_instance_server" "scaleway_instance" {
  name  = "fr-vm-test-instance"
  type  =   "DEV1-M"
  image     = "ubuntu_focal"
  boot_type = "local"
  
  enable_dynamic_ip = true
  security_group_id = scaleway_instance_security_group.scaleway_instance_sg.id
  
  additional_volume_ids = [ scaleway_instance_volume.additional_volume.id ]

  root_volume {
    size_in_gb = 20
  }
}
```

### Debug Output

All resources properly deployed: 
```
Apply complete! Resources: 4 added, 0 changed, 0 destroyed.
```

However, I could not access to my instance, neither via SSH (Connexion timeout) nor via console.

When deep diving the problem on the console, I see that start http boot over ipv4 is not working.

### Expected Behavior

scaleway_instance_server properly deployed and accessible via SSH

### Actual Behavior

scaleway_instance_server properly deployed  but not accessible via SSH and not booted correctly

### Steps to Reproduce

1. `terraform apply`
2. ssh -i <private_key> root@<instance_public_ip>

### References

* #0000

**Comment by remyleone** [comment]
Hello, this is not a problem with terraform but rather with the instances. So I will be closing it for now, feel free to reopen if you have a snippet of terraform code that can reproduce your issue.

Sometimes it can take a bit of time between the moment where terraform complete the instation of your resources and the moment where the SSH daemon is up and ready to accept incoming connections. So that might be an issue. One way to test that is to test after one minute or two to be sure that the SSH daemon had plenty of time to start.

Also are you sure that the proper SSH keys are available on your organization account and properly deployed on your instance ? Can you connect after some moment to your instance manually ?

**Comment by elghali97** [comment]
Hello @remyleone ! 

I've deployed all my resources this morning using terraform, and my instance is still not accessible via SSH or Scaleway web console. 

The proper SSH keys are available on my organization account et properly associated to my account (I've tried to reboot my instance rescue mode and it worked well !). 

However, as mentioned previously, the problem is not on the SSH daemon, but on booting step, as `start http boot over ipv4` command does not work.

You can reproduce just with my snippet (previously mentioned too):

```
resource "scaleway_instance_security_group" "scaleway_instance_sg" {
  name                    = "fr-sg-test-instance"
  description             = "Allow TLS inbound traffic"
  inbound_default_policy  = "drop"
  outbound_default_policy = "accept"

  inbound_rule {
    action = "accept"
    port   = "22"
  }

  inbound_rule {
    action = "accept"
    port   = "80"
  }

  inbound_rule {
    action = "accept"
    port   = "443"
  }
}

resource "scaleway_instance_volume" "additional_volume" {
  size_in_gb = 20
  type = "l_ssd"
}

resource "scaleway_instance_server" "scaleway_instance" {
  name  = "fr-vm-test-instance"
  type  =   "DEV1-M"
  image     = "ubuntu_focal"
  boot_type = "local"
  
  enable_dynamic_ip = true
  security_group_id = scaleway_instance_security_group.scaleway_instance_sg.id
  
  additional_volume_ids = [ scaleway_instance_volume.additional_volume.id ]

  root_volume {
    size_in_gb = 20
  }
}
```

**Comment by trilliot** [comment]
Same issue here. Using the official example (https://registry.terraform.io/providers/scaleway/scaleway/latest/docs), I am not able to boot an instance on Scaleway with Terraform (tested on multiple regions without success).
It works well via the Web Console.

State is applied, resources are created, but the server never boots.  
A call to the API gives insight about the actual state of the server :
```
"state_detail": "booting kernel",
```

**Comment by clementnero** [comment]
Hello,
I have the same problem as well. When opening the Console I get the UEFI Interactive Shell.

**Comment by Codelax** [comment]
Hi, sorry for inconvenience, a fix is on the way, it will be released right after
