### ISSUE TITLE
Container name not used when creating a registry

### ISSUE THREAD

**Issue by juchom** [scaleway/terraform-provider-scaleway#1417]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.2.6
scaleway/scaleway v2.2.7

### Affected Resource(s)

* Container registry

### Terraform Configuration Files

```hcl
resource "scaleway_container_namespace" "main" {
  name        = "my-abc-registry"
}
```

### Expected Behavior

the registry should be named `my-abc-registry`

### Actual Behavior

![image](https://user-images.githubusercontent.com/17902415/185082826-9c7a0986-67a5-4580-b1bc-36ee79cb879e.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by Codelax** [comment]
Hi, thanks you for reporting, what you create is a [serverless container](https://www.scaleway.com/en/serverless-containers/) namespace, not a [container registry](https://www.scaleway.com/en/container-registry/) namespace.
When you create a serverless container namespace, a registry namespace is created with it using a random name, this is done by the serverless product and not controlled by the terraform provider.

You can look at registry_namespace [documentation](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/registry_namespace) if this is what you wanted

**Comment by juchom** [comment]
Ho crap, I went to fast, sorry for that. :(

Thanks for the quick reply !
