### ISSUE TITLE
Support for secret environment variables in Serverless Containers

### ISSUE THREAD

**Issue by rclement** [scaleway/terraform-provider-scaleway#1431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for "Secret Environment Variables" in Serverless Containers.

Please add the `secret_environment_variables` argument for:
- [Container Namespace](https://developers.scaleway.com/en/products/containers/api/#secret-environment-variables-ee68a9)
- [Container](https://developers.scaleway.com/en/products/containers/api/#secret-environment-variables-69183d)

### New or Affected Resource(s)

* scaleway_container_namespace
* scaleway_container

**Comment by Codelax** [comment]
Implemented, will be included in next release
