### ISSUE TITLE
redis acl block accepts non-cidr IPs and will result in unstable resources

### ISSUE THREAD

**Issue by vdmkenny** [scaleway/terraform-provider-scaleway#1459]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.2.8

### Affected Resource(s)
scaleway_redis_cluster(.acl)

### Terraform Configuration Files

```hcl
resource "scaleway_redis_cluster" "main" {

...

  acl {
    ip = "1.2.3.4"
    description = "Allow 1.2.3.4"
  }
}
```

### Expected Behavior

This should either not be accepted, or else not result in unstable resources

### Actual Behavior

The scaleway API accepts `1.2.3.4` formatted IPs, but automatically converts them to `1.2.3.4/32`, resulting in changes on every terraform apply.

```hcl
Terraform will perform the following actions:
  # scaleway_redis_cluster.rage will be updated in-place
  ~ resource "scaleway_redis_cluster" "example" {
        id           = "XXXXXXX"
        name         = "example"
      - acl {
          - description = "allow 1.2.3.4" -> null
          - id          = "XXXX" -> null
          - ip          = "1.2.3.4/32" -> null
        }
      + acl {
          + description = "scw-adimian-test-adimian-k8s-test-5dddb01e31e8"
          + id          = (known after apply)
          + ip          = "1.2.3.4"
        }
```

Note: this does not seem to be the case with the rdb acl, here a proper CIDR seems to be enforced.

**Comment by Monitob** [comment]
Thanks for the report. It will be available in our next release
