### ISSUE TITLE
downsizing a redis instance size should not be allowed

### ISSUE THREAD

**Issue by vdmkenny** [scaleway/terraform-provider-scaleway#1461]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
1.2.9

### Affected Resource(s)

* scleway_redis_cluster

### Terraform Configuration Files

![image](https://user-images.githubusercontent.com/17249209/189360030-9ed1fe5b-a460-44f9-bad6-ef47507c7894.png)

### Panic Output

![image](https://user-images.githubusercontent.com/17249209/189360212-9e7b10aa-9cae-4c8f-a4de-c6b0aff95b10.png)

### Expected Behavior

Since this action is not allowed/possible in the UI, it should not be allowed here. The provider should notice the downsize and throw an error during the planning stage.

### Actual Behavior

See panic output. It made an attempt but failed.

### Steps to Reproduce

Increase the instance size of a redis cluster and attempt to lower it again, see config file diff.

1. `terraform apply`

**Comment by Monitob** [comment]
Thank you for the ticket. The check is now handled on the API and the resource will not pass in the `provisioning` state:

```
│ Error: scaleway-sdk-go: invalid argument(s): node_type does not respect constraint, Cannot migrate to a node_type with less or equals memory
```
