### ISSUE TITLE
Resource Instance UserData

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#1470]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Attributes `cloud_init` and `user_data` looks duplicated and hard to manage as part of the resource instance server.

This is not the desired behavior on an instance_server. Please consider add new resource_instace_user_data

### New or Affected Resource(s)

* scaleway_instance_user_data

### Potential Terraform Configuration

```hcl
resource scaleway_instance_server main {
...
}

resource scaleway_instance_user_data   main {
  server_id = scaleway_intance_server.main.id 
  cloud_init = jsonencode(
apt_update=true
apt_upgrade= true)
}

or 

resource scaleway_instance_user_data {
   server_group_ids = [scaleway_instance_server.main.id,....]
   user_data = {
							cloud-init = <<EOF
#cloud-config
apt_update: true
apt_upgrade: true
EOF
	}
}
```

### References

Please check the endpoint on Scaleway SDK https://github.com/scaleway/scaleway-sdk-go/blob/master/api/instance/v1/server_utils.go#L242

* #848

**Comment by Codelax** [comment]
List of server is not needed as you can use terraform syntax
```hcl
resource scaleway_instance_server "servers" {
  count = 5
  ...
}

resource scaleway_instance_user_data   main {
  for_each = scaleway_instance_server.servers
  server_id = each.value.id
  cloud_init = jsonencode(
  apt_update=true
  apt_upgrade= true)
}

```

**Comment by Monitob** [comment]
May be  another proposition is
```hcl
resource scaleway_instance_server "servers" {
  count = 5
  ...
}

resource scaleway_instance_user_data   main {
  for_each = scaleway_instance_server.servers
  server_id = each.value.id
  setting  {
  value = "apt_update=true"
 }
```

**Comment by Codelax** [comment]
With a single key per resource
```
variable user_data {
  default = [
    {
      key: 'cloud_init',
      value: 'aa'
    },
    {
      key: 'other',
      value: 'bb',
    }
  ]
}

resource scaleway_instance_user_data data {
  for_each = toset(var.user_data)
  key = each.key
  value = each.value
}
```

With a single resource for multiple key
```
resource scaleway_instance_user_data data {
  for_each = toset(var.user_data)
  dynamic "setting" {
    for_each = toset(var.user_data)
    content {
      key = each.key
      value = each.value
    }
  }
}
```
Problem of a single resource is that our resource will replace all user_data and we still need to make multiple request, no gain.

**Comment by Monitob** [comment]
Yeah, like it. Pretty good approach. I'm gonna keep this 
```
resource scaleway_instance_user_data data {
  for_each = toset(var.user_data)
  key = each.key
  value = each.value
}
```

Thanks @Codelax
