### ISSUE TITLE
scaleway_container removes environment variables

### ISSUE THREAD

**Issue by boredland-ioki** [scaleway/terraform-provider-scaleway#1471]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.3.0-dev
on linux_amd64
+ provider registry.terraform.io/gitlabhq/gitlab v3.18.0
+ provider registry.terraform.io/hashicorp/random v3.4.3
+ provider registry.terraform.io/scaleway/scaleway v2.2.9
```

### Affected Resource(s)

* scaleway_container

### Terraform Configuration Files

```hcl
resource "scaleway_container" "somecontainer" {
  name                = "somecontainer"
  namespace_id  = scaleway_container_namespace.somenamespace.id
  memory_limit    = 2048
  min_scale         = 0
  max_scale        = 1
  privacy              = "public"
}
```

### Expected Behavior

When setting environment variables (using the scw cli or the web interface), I would expect those to remain after applying the terraform state, at least if I don't provide them in the resource. This behaviour also could be managed via a dedicated flag "remove_variables" or so.

### Actual Behavior

All environment variables are removed from the container.

```
resource "scaleway_container" "somecontainer" {
      ~ environment_variables = {
          - "SOMEVAR" = "someval" -> null
          - "SOMEVAR2"      = "someval2" -> null
        }
        id                    = "fr-par/xxx"
        name                  = "somecontainer"
        # (16 unchanged attributes hidden)
}
```

**Comment by Codelax** [comment]
Hi ! Thanks you for reporting, fix will be in next release.
