### ISSUE TITLE
scaleway_domain_record not found after creation

### ISSUE THREAD

**Issue by boredland-ioki** [scaleway/terraform-provider-scaleway#1479]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_domain_record

### Terraform Configuration Files

```hcl
resource "scaleway_domain_record" "cname" {
  dns_zone = var.dns_zone_id
  name     = var.subdomain
  type     = "CNAME"
  data     = "xxx.scw.cloud"
}
```

### Debug Output

```
scaleway_domain_record.cname: Creating...
scaleway_domain_record.cname: Still creating... [10s elapsed]
╷
│ Error: record with data xxx.scw.cloud not found
│ 
│   with scaleway_domain_record.cname,
│   on main.tf line 10, in resource "scaleway_domain_record" "cname":
│   10: resource "scaleway_domain_record" "cname" {
```

### Expected Behavior

the resource is created and the terraform state is updated.

### Actual Behavior

the resource is being created (confirmed via the scw console), but the state is not updated.

### Steps to Reproduce

1. `terraform apply`

**Comment by Codelax** [comment]
Hi ! Thanks you for reporting this issue. This is due to api that modify data content for cname, data `xxx.scw.cloud` becomes `xxx.scw.cloud.subdomain.domain.tld.`, currently our provider fails to fetch it after creation as it is strict on data content.
