### ISSUE TITLE
Resource Instance: Import failed on image attribute

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#1483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_server" "main" {
	image = "ubuntu_focal"
	type  = "DEV1-S"
}
```

### Debug Output

```shell
 resource_instance:  ImportStateVerify attributes not equivalent. The difference is shown below. The top is actual, and the bottom is expected.
        
        (map[string]string) (len=1) {
         (string) (len=5) "image": (string) (len=45) "fr-par-1/64dc7755-9499-43af-8b68-b01e10325ee7"
        }
        
        
        (map[string]string) (len=1) {
         (string) (len=5) "image": (string) (len=12) "ubuntu_focal"
        }
```

### Steps to Reproduce

When adding `ImportStateVerify: true` to verify the state the image will be replaced by the id of the image 

### References

* #0000

**Comment by remyleone** [comment]
That's why the data resource is there for.

**Comment by Monitob** [comment]
the data source looks like a workaround. We should consider apply the option `StateFunc` on the [schema](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#SchemaStateFunc)

**Comment by Monitob** [comment]
Close due to `ImportStateVerify` inconsistency and `StateFunc` is not recommended to set and ID. More information [here](https://github.com/hashicorp/terraform/issues/20985)
