### ISSUE TITLE
[IAM] default_project_id in the scaleway_iam_api_key resource is not taken into account

### ISSUE THREAD

**Issue by zandolsi-psee** [scaleway/terraform-provider-scaleway#1527]
Hi,

The `default_project_id` attribute in the `scaleway_iam_api_key` resource is not taken into account. In fact when creating an api key with terraform, the key is created but always associated to the organization's default project and not the project passed as attribut in the resource.

terraform version: 1.3.1
scaleway provider version: 2.4.0

**Comment by Codelax** [comment]
Fixed in #1537
