### ISSUE TITLE
Baremetal: add options flag private network

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#1528]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please enable the [Options](https://pkg.go.dev/github.com/scaleway/scaleway-sdk-go@v1.0.0-beta.9/api/baremetal/v1#CreateServerRequest) flag when creating a server. This will allow enable the private Network attachment

https://www.scaleway.com/en/docs/compute/elastic-metal/how-to/use-private-networks/

#### DataSource
* scaleway_baremetal_option

#### Resource

* scaleway_baremetal_server
* * scaleway_baremetal_private_network

- [x] #1615
- [x] #1649
- [x] #1629

### Potential Terraform Configuration

```hcl
resource "scaleway_account_ssh_key" "main" {
  name 	   = "%s"
  public_key = "%s"
}

resource "scaleway_baremetal_server" "base" {
  name        = "%s"
  zone        = "fr-par-2"
  description = "test a description"
  offer       = "GP-BM1-M"
  os          = "d17d6872-0412-45d9-a198-af82c34d3c5c"

  tags = [ "terraform-test", "scaleway_baremetal_server", "minimal" ]
  ssh_key_ids = [ scaleway_account_ssh_key.main.id ]
  options_ids = [scaleway_baremetal_option.private_network.id, scaleway_baremetal_option.remote_access.id]
}

resource "scaleway_baremetal_option" "private_network" {
  name        = "PrivateNetwork"
}

resource "scaleway_baremetal_option" "remote_access" {
  name        = "RemoteAccess"
}

resource scaleway_vpc_private_network pn {}

resource "scaleway_baremetal_private_network" "main" {
               server_id = scaleway_baremetal_server.main.id
               private_network_id = scaleway_vpc_private_network.pn.id
      }
```
### References

* #0000

**Comment by remyleone** [comment]
Should be a data source and not really a resource. There is nothing to configure in the option, it is a pure read only. Customer do not mutate an option.
