### ISSUE TITLE
Bug: k8s cluster version with 3 digits failing

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#1532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

provider 2.4.0 

### Affected Resource(s)

* scaleway_k8s_cluster

### Terraform Configuration Files

```hcl
resource "scaleway_k8s_cluster" "k8s" {
  ...
  version = x.y.z
  auto_upgrade = {
    enable = true
    ...
  }
}
```

### Panic Output

```minor version x.y must be used with auto upgrades enabled```

### Actual Behavior

When we define a cluster version with 3 digits with auto_upgrade enabled
`terraform plan` don’t detect any problem but the `terraform apply` failed

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by fdrouet** [comment]
### Expected Behavior

`terraform plan` should raise an error
