### ISSUE TITLE
Unable to create instance with existing volume

### ISSUE THREAD

**Issue by lucas-flis** [scaleway/terraform-provider-scaleway#1547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.3.3
on darwin_arm64
+ provider registry.terraform.io/scaleway/scaleway v2.5.0
```

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_volume" "scw-volume-root-01" {
    type        = "b_ssd"
    name        = "ubuntu_22.04-root"
    size_in_gb  = 20
}

resource scaleway_instance_server "scw-terraform-01" {
  name      = "scw-terraform-01"
  image     = "2289fad9-2694-48ab-bb41-f19e4a9a8584"
  type      = "PLAY2-PICO"
  tags      = [ "terraform" ]
  root_volume {
    volume_id = scaleway_instance_volume.scw-volume-root-01.id
    delete_on_termination = false
  }
  depends_on = [
    scaleway_instance_volume.scw-volume-root-01,
  ]
}
```

### Debug Output

https://gist.github.com/lucas-flis/f655aedc8f560659e0131cd9fe33382c

### Expected Behavior

Create an instance with provided volume, according to the [documentation](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/instance_server#root_volume) 

### Actual Behavior

Create only volume, and failed to create instance with this error
```
╷
│ Error: scaleway-sdk-go: invalid argument(s): volumes.0.name does not respect constraint, required key not provided
│
│   with scaleway_instance_server.scw-terraform-01,
│   on main.tf line 25, in resource "scaleway_instance_server" "scw-terraform-01":
│   25: resource scaleway_instance_server "scw-terraform-01" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`

**Comment by Codelax** [comment]
Hi, you cannot create an instance with a root_volume_id and an image. Instance will not install image on your already created volume so you can just remove `image` attribute

**Comment by Codelax** [comment]
Also when creating an instance, you are not required to use an image id, you can use `ubuntu_jammy` and terraform will fetch id corresponding to your image
```hcl
resource scaleway_instance_server "scw-terraform-01" {
  name      = "scw-terraform-01"
  image     = "ubuntu_jammy"
  type      = "PLAY2-PICO"
}
```

**Comment by Codelax** [comment]
Thanks for reporting this, I created an [issue](https://github.com/scaleway/terraform-provider-scaleway/issues/1548) to improve our documentation and error handling
