### ISSUE TITLE
instance: wait for private_nic before starting instance

### ISSUE THREAD

**Issue by Codelax** [scaleway/terraform-provider-scaleway#1571]
When creating an instance_server and an instance_private_nic, server may be started before private network is connected, this can make network setup miss private network.
It leads to non-working DHCP leasing and requires instance reboot to fix the issue.
This should be investigated to see if we can add a feature to make server wait before pn setup or restart after.

**Comment by remyleone** [comment]
Maybe we could solve this by adding a wait condition on the server in this resource: https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_instance_private_nic.go#L55

**Comment by Timost** [comment]
Some more context, I noticed that it takes https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/vpc_public_gateway_dhcp#renew_timer to fix the issue so the reboot is not strictly necessary but with default settings (50 minutes) it takes a long time.

My current work around is to wait for the interface to show up in the init process (custom initramfs-tools script)

I'm not sure it's possible but maybe we could start creating the private nic as soon as we have a `id` for the server instance ?
Right now it seems, we wait for the server to be up before starting creating the private nic but it seems the api simply requires the server id.

**Comment by Monitob** [comment]
In the case of `private_nic`, checking the instance's state is a good first step. Maybe something to consider in all `private_network` integration.
