### ISSUE TITLE
Cleanup and improve error message for letsencrypt failure

### ISSUE THREAD

**Issue by NicolasCARPi** [scaleway/terraform-provider-scaleway#1613]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello!

When using scaleway_lb_certificate with letsencrypt, it might happen that the certificate obtention fails (for instance dns is incorrect). I see two issues:

1/ The new (not working/incomplete) certificate is created and visible in red in the web console on the Load Balancers > SSL Certificates tab. So it is not cleaned up after failure, but more importantly, another plan after that will result in error because of its presence. It needs to be manually removed from web console ui so another plan will work (could not get plan error message as it is not stored in terraform web ui).

2/ The error message for an error during cert obtention is not informative:

~~~
Error: certificate XXX-YYY-ZZZ with error state
with scaleway_lb_certificate.main
on my_file.tf line 49, in resource "scaleway_lb_certificate" "main":

resource "scaleway_lb_certificate" "main" {
~~~

It would be great if this could be improved somehow.

### New or Affected Resource(s)

* scaleway_lb_certificate

### Example configuration

~~~hcl
resource "scaleway_lb_certificate" "main" {
  lb_id = scaleway_lb.main.id
  name  = "cert main"

  letsencrypt {
    common_name = "${replace(scaleway_lb_ip.main.ip_address,".", "-")}.lb.${scaleway_lb.main.region}.scw.cloud"
    subject_alternative_name = ["example.com", "another.example.com"]
  }
  lifecycle {
    create_before_destroy = true
  }
}
~~~

Best,
~Nico

**Comment by NicolasCARPi** [comment]
@yfodil Yes.

**Comment by yfodil** [comment]
Can you try to run it with those two env variables please:
`SCW_DEBUG=1 TF_LOG=WARN TF_LOG_PROVIDER=DEBUG terraform apply`

It will increase the logs level of terraform and will print all requests and their responses which will help to investigate

**Comment by NicolasCARPi** [comment]
Ok will try that next time, thanks!
