### ISSUE TITLE
rdb: rework rdb_instance endpoints

### ISSUE THREAD

**Issue by Codelax** [scaleway/terraform-provider-scaleway#1653]
https://developers.scaleway.com/en/products/rdb/api/#endpoints-c7161b

RDB product features an almost complete CRUD (no update), this should be enough to implement its usage as a standalone ressource that use all its features (private_network, loadbalancer, direct_access).

Currently, we only support private_network as a rdb_instance attribute.

The problem is that an instance can take a list of init_endpoints to create it with endpoints, it also probably have already created endpoints (direct_access) per default. 
How can default endpoints be managed in terraform ? Can we delete them ? Can we add more direct_access ?
This should be sorted out with the team.

**Comment by Monitob** [comment]
Well done. I'm ok to build a new resource without an update in this case. In this case, Maybe consider deprecating all the attributes concerning the endpoints. Resource [ticket](https://github.com/scaleway/terraform-provider-scaleway/issues/1654)

**Comment by abarbare** [comment]
Hello, 

The current behaviour of RDB is the following one:

You always have a public endpoint (type `loadbalancer`) on your RDB instance. Even if you only specified `private_network` in the `init_endpoints` you will get a `load_balancer` as well. 

`direct_access` endpoint are for now reserved to read replicas and don't exist (yet?) on RDB instances. 

You can't have more than 1 public access on both your RDB instance or your Read Replica: respectively `loadbalancer` and `direct_access` endpoint type. 

The only endpoint you can operate is the `private_network` one. You can add at most one `private_network` on both RDB instance or Read Replica. It could be a different one between your RDB instance and the Read Replica. 
A `private_network` endpoint can't be updated, you have to delete and recreate it if you want to update it (like the IP).
