### ISSUE TITLE
Allow users to specify the project a bucket should belong to

### ISSUE THREAD

**Issue by rbarrois** [scaleway/terraform-provider-scaleway#1667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Each bucket should be linked to a specific project.
Currently, it is not possible to choose said project at the bucket level; thus, we need to rely on the "default" project linked to the API key.
It would be helpful to be able to either be able to set the owner project, or at least to provide an "expected_project_id", and having terraform bail out if the bucket is not linked to the right project.

### New or Affected Resource(s)

* scaleway_object_bucket

### Potential Terraform Configuration

```hcl
resource "scaleway_object_bucket" "my_bucket" {
  name = "some-example-bucket"
  region = "fr-par"
  project_id = scaleway_account_project.some_project.id
}
```

**Comment by Codelax** [comment]
Hi, thanks for creating this issue.

Creating a bucket on a different project than the access_key's default can be achieved using `access_key@project-id` in aws requests.
This was made for our website, we need to figure out if this can be used in the terraform provider.

Otherwise you should be able to create a different provider with a new access_key:

```hcl
resource "scaleway_iam_application" "main" {
  name = "My application"
}

resource "scaleway_iam_api_key" "main" {
  application_id = scaleway_iam_application.main.id
  default_project_id = "xxxx-xxxx"
}

resource scaleway_iam_policy "object_full_access" {
  name = "object full access"
  application_id = scaleway_iam_application.main.id
  rule {
    project_ids = [scaleway_iam_api_key.main.default_project_id]
    permission_set_names = ["ObjectStorageFullAccess"]
  }
}

provider scaleway {
  alias = "object"
  access_key = scaleway_iam_api_key.main.access_key
  secret_key = scaleway_iam_api_key.main.secret_key
}

resource scaleway_object_bucket my_bucket {
  provider = scaleway.object
  name = "mybucketname"
  region = "fr-par"
  depends_on = [scaleway_iam_policy.object_full_access]
}
```

In this example I created an application to possess this new api_key but you can create it for your user to skip the needed iam_policy.

**Comment by rbarrois** [comment]
Thanks for the workaround; this is indeed the way we're trying to use for now (despite severe issues with both bucket and application resources).

However, I'm not sure your example code would work — if I remember correctly, terraform expects providers' configuration to be known at the start; they can't rely on other resources data.
Thus, one would need *two* terraform projects: one to create the project and its application; and a second one to manage the bucket.

This could make sense if it's the recommended Scaleway setup, but I haven't found any docs to that end — most example assume a single set of keys for managing the whole Scaleway project (and guidance for other platforms assume one would split projects across accounts for increased security).

**Comment by Codelax** [comment]
The provider configuration needs to been known before creating resources but you can have multiple provider configurations.

With the snippet I given before I create a provider with an alias but you can consider the default provider to be already created.

```hcl
provider scaleway { // Default
}

resource "scaleway_iam_api_key" "main" { // Use Default provider
  application_id = scaleway_iam_application.main.id
  default_project_id = "xxxx-xxxx"
}

provider scaleway { // Create a new provider
  alias = "object"
  access_key = scaleway_iam_api_key.main.access_key
  secret_key = scaleway_iam_api_key.main.secret_key
}

resource scaleway_object_bucket my_bucket { // Use newly created provider
  provider = scaleway.object
}
```

A provider can be created like a terraform resource.

**Comment by quantumsheep** [comment]
@rbarrois Is this still an issue?

**Comment by rbarrois** [comment]
@quantumsheep I'd say so, unless other changes have addressed the topic at hand.

The proposed implementation requires one to put some API secret keys in Terraform state, which is not always compatible with one's security policy.

Another option would be to use dedicated admin API keys for terraforming each project; however, that pattern isn't suggested in Scaleway's documentation; and doesn't allow for fine-grained access control on buckets.
Indeed, since bucket policies work at the "project" level, a fine-grained policy requires one project per granted access level/application; the terraform project thus needs to juggle a few projects, and users will likely create all projects (the "bucket owner" project and all "bucket user" projects) in the same terraform module.

Once bucket policy can restrict access based on an IAM application, it would be simpler to create projects through an account-wide master Terraform project, and having one terraform module for each "project" — planned and applied with admin access keys scoped to said project.
