### ISSUE TITLE
scaleway_k8s_cluster: new attribute containing raw id

### ISSUE THREAD

**Issue by Codelax** [scaleway/terraform-provider-scaleway#1723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new `regional_id` attribute with the only the id unlike the default `id` attribute (`{region}/{cluster_id}`)

### New or Affected Resource(s)

* scaleway_kubernetes_cluster

### References

Created from a request on scaleway's community slack and https://feature-request.scaleway.com/posts/562/strip-region-prefix-from-response-parameter-scaleway_k8s_cluster-id

**Comment by Mia-Cross** [comment]
The documentation has been updated, we have added :
- we have added [examples](https://github.com/scaleway/terraform-provider-scaleway/blob/master/docs/guides/regions_and_zones.md#resource-ids) of code to retrieve the raw id if you need it outside of Terraform. 
- we have reviewed all resources and data sources documentation to make sure that the form of the identifier was specified.

Hope this helps.
