### ISSUE TITLE
Expose RDB endpoint for the instance

### ISSUE THREAD

**Issue by suda** [scaleway/terraform-provider-scaleway#1836]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After creating an RDB instance/database/user via Terraform, it would be great to get the endpoint's address and port to set it in a Kubernetes secret for example. The endpoints are [already exposed in the API](https://developers.scaleway.com/en/products/rdb/api/#how-to-connect-to-your-instance) but we're missing those fields in the Terraform data source.

### New or Affected Resource(s)

* scaleway_rdb_instance

### Potential Terraform Configuration

```hcl
data "scaleway_rdb_instance" "my_instance" {
  name = "foobar"

  endpoint {
    ip: "xxx.xxx.xxx.xxx",
    port: 22245
  }
}
```

### References

Some tickets were created and closed without a clear resolution:
* #1653
* #1654

**Comment by Monitob** [comment]
Hello @suda, all the exported attributes are the ones from the resource. I'll bump de documentation and thanks for the feedback.

Here an example to get the ip address:

```hcl
  data "scaleway_rdb_instance" "main" {
    instance_id = scaleway_rdb_instance.main.id
  }

  output "loadbalancer_ip_addr" {
    value = scaleway_rdb_instance.main.load_balancer.0.ip
  }
```

**Comment by suda** [comment]
Ah, that's great, thank you!

**Comment by Monitob** [comment]
FYI: I've just added the example on #1842
