### ISSUE TITLE
Issue while upgrading scaleway_k8s_cluster from 1.23 to 1.24

### ISSUE THREAD

**Issue by bertrandp** [scaleway/terraform-provider-scaleway#1840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.4.0
on darwin_amd64
+ provider registry.terraform.io/carlpett/sops v0.5.3
+ provider registry.terraform.io/hashicorp/kubernetes v1.13.4
+ provider registry.terraform.io/scaleway/scaleway v2.13.1

### Affected Resource(s)

* scaleway_k8s_cluster

### Terraform Configuration Files

The cluster I want to upgrade (with one pool) :
```hcl
resource "scaleway_k8s_cluster" "ams-dev-1" {
  provider = scaleway.apollon-dev
  name             = "ams-dev-1"
  region           = "nl-ams"
  version          = "1.23"  # -> 1.24
  cni              = "calico"
  delete_additional_resources = false
  tags             = ["dev", "sunr"]
  admission_plugins = ["PodNodeSelector"]
  autoscaler_config {
    disable_scale_down              = false
    scale_down_delay_after_add      = "5m"
    estimator                       = "binpacking"
    expander                        = "random"
    ignore_daemonsets_utilization   = true
    balance_similar_node_groups     = true
    expendable_pods_priority_cutoff = -5
  }

  auto_upgrade {
    enable                        = true
    maintenance_window_day        = "tuesday"
    maintenance_window_start_hour = 4
  }
}

resource "scaleway_k8s_pool" "app-1" {
  cluster_id = scaleway_k8s_cluster.ams-dev-1.id
  name       = "app-1"
  container_runtime  = "containerd"
  node_type  = "DEV1-L"
  size                = 1
  autoscaling         = true
  autohealing         = true
  min_size            = 1
  max_size            = 4
  tags                = ["env=dev","app=web", "app=compute"]
  wait_for_pool_ready = true
  provider            = scaleway.apollon-dev
}
```
A resource related to an ingress, I don't know if it's relevant :
```hcl
resource "scaleway_lb_ip" "traefik-ams-ip" {
  provider = scaleway.apollon-dev
}

resource "scaleway_lb" "traefik-ams-lb" {
  ip_id  = scaleway_lb_ip.traefik-ams-ip.id
  type   = "LB-S"
}

resource "kubernetes_service" "traefik-ams-dev" {
  provider = kubernetes.kubernetes-ams-dev
  metadata {
    name      = "traefik"
    namespace = "kube-system"
    labels = {
      "k8s.scw.cloud/ingress"    = "traefik2"
      "k8s.scaleway.com/cluster" = split("/", scaleway_k8s_cluster.ams-dev-1.id)[1]
    }
  }
  spec {
    type             = "LoadBalancer"
    load_balancer_ip = scaleway_lb_ip.traefik-ams-ip.ip_address
    external_traffic_policy     = "Local"
    port {
      port        = 80
      name        = "http"
      target_port = "8000"
    }
    port {
      port        = 443
      name        = "https"
      target_port = "8443"
    }
    selector = {
      "app.kubernetes.io/name" : "traefik"
    }
  }
}
```

### Debug Output

```
(...)
  # scaleway_k8s_cluster.ams-dev-1 will be updated in-place
  ~ resource "scaleway_k8s_cluster" "ams-dev-1" {
        id                          = "nl-ams/22b4a1c6-2697-421c-9322-ba6657c40eff"
        name                        = "ams-dev-1"
        tags                        = [
            "dev",
            "sunr",
        ]
      ~ version                     = "1.23" -> "1.24"
        # (17 unchanged attributes hidden)

        # (3 unchanged blocks hidden)
    }

Plan: 0 to add, 3 to change, 0 to destroy.
(...)
scaleway_k8s_cluster.ams-dev-1: Still modifying... [id=nl-ams/22b4a1c6-2697-421c-9322-ba6657c40eff, 1m0s elapsed]
╷
│ Error: scaleway-sdk-go: invalid argument(s): ingress does not respect constraint, this version is not available with the current ingress
│ 
│   with scaleway_k8s_cluster.ams-dev-1,
│   on dev-ams-cluster.tf line 2, in resource "scaleway_k8s_cluster" "ams-dev-1":
│    2: resource "scaleway_k8s_cluster" "ams-dev-1" {
│ 
╵
```
Part of the debug log : https://gist.github.com/bertrandp/3468be41c3e95464c489fec51ff74c94 

### Expected Behavior

I want to upgrade my Kubernetes cluster from 1.23 to 1.24, using terraform apply

### Actual Behavior

Failed to upgrade to 1.24

### Steps to Reproduce

1. Change version from 1.23 to 1.24 in the terraform file
2. `terraform apply`

### References

* #0000

**Comment by remyleone** [comment]
Hello 👋 could you try to do `scw k8s cluster update XXX ingress=none` with the [scaleway-cli](https://github.com/scaleway/scaleway-cli) ?

**Comment by jtherin** [comment]
I see that your cluster is using managed Ingress traefik2. The feature was **deprecated because many users edited their managed ingress controller configuration and complained that during upgrades their changes were overwritten**.

So to avoid complains, we removed managed ingress field on terraform provider 2.0 and console.

Clusters that previously had a managed ingress can still use it up to 1.23, after 1.24 we completely removed the managed ingress support. If you want to upgrade to 1.24+, you have to set `ingress` field to `none` though cli with `scw k8s cluster update $CLUSTER_ID ingress=none` or through API.
