### ISSUE TITLE
Private NIC already exist

### ISSUE THREAD

**Issue by ygwane** [scaleway/terraform-provider-scaleway#1856]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.3.9

### Affected Resource(s)

* scaleway_instance_private_nic

### Terraform Configuration Files

```hcl
# create project
resource "scaleway_account_project" "project" {
  name = "project"
  organization_id = "${var.organization_id}"
}
# create private network
resource "scaleway_vpc_private_network" "pn01" {
  name = "private_subnet"
  project_id = "${scaleway_account_project.project.id}"
}

# create managers ip public addresses
resource "scaleway_instance_ip" "public_ip-manager" {
  count = "${var.instance_manager_count}"
  project_id = "${scaleway_account_project.project.id}"
}

# create managers instances
resource "scaleway_instance_server" "manager" {
  count = "${var.instance_manager_count}"
  name = "manager-${count.index + 1}"
  project_id = "${scaleway_account_project.project.id}"
  type  = "${var.instance_type}"
  image = "${var.image_type}"
  tags = [ "manager", "swarm", "swarm_manager" ]
  security_group_id= "${scaleway_instance_security_group.managers.id}"
  ip_id = "${element(scaleway_instance_ip.public_ip-manager.*.id, count.index)}"
  private_network {
    pn_id = "${scaleway_vpc_private_network.pn01.id}"
  }
  root_volume {
    size_in_gb = "${var.instance_manager_size}"
  }
}

# create managers ip private addresses
resource "scaleway_instance_private_nic" "pmanagernic" {
  count = "${var.instance_manager_count}"
  server_id = "${element(scaleway_instance_server.manager.*.id, count.index)}"
  private_network_id = "${scaleway_vpc_private_network.pn01.id}"
}
```

### Actual Behavior

I'm trying to create a docker swarm cluster with scaleway terraform provider. To simplify process, I work with a count that will create X public IP for X server instances.

To secure environment, I want to use private network but it seems to be not possible to create various private nic interfaces based on count. 
scaleway_instance_private_nic resource does not support name argument, so following issue happening on terraform apply:
`Error: scaleway-sdk-go: invalid argument(s): private_nics does not respect constraint, Private NIC already exist
`

I would like to know ihow to do this or if another way is possible to do that ?

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Codelax** [comment]
```
# create managers instances
resource "scaleway_instance_server" "manager" {
  private_network {
    pn_id = "${scaleway_vpc_private_network.pn01.id}"
  }
}

# create managers ip private addresses
resource "scaleway_instance_private_nic" "pmanagernic" {
  count = "${var.instance_manager_count}"
  server_id = "${element(scaleway_instance_server.manager.*.id, count.index)}"
  private_network_id = "${scaleway_vpc_private_network.pn01.id}"
}
```

`private_network` attribute in instance_server is a duplicate fonctionality of `scaleway_instance_private_nic`.
You should use `scaleway_instance_private_nic` instead of `private_network` and not both

**Comment by ygwane** [comment]
Indeed, it works better like this. Thanks
