### ISSUE TITLE
Resource MNQ enhacement

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#1874]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_mnq_XXXX

### Expected Behavior

- [x] On the [credential page](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/mnq_credential) on the documentation, the title should be  `scaleway_mnq_namespace`

- [x] The nats_credentials  is described as an argument instead of an attribute

- [ ] The nats_credentials  attribute is an array but only has one element so to use it we need an extra [0] to access it.

- [x] [guide doc](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/guides/mnq_with_nats_terraform_provider)  typo on example scaleway_mnq_namespace.manin.endpoint should be scaleway_mnq_namespace.main.endpoint

**Comment by Codelax** [comment]
These olds resources have been deleted after depreciation of the old API
