### ISSUE TITLE
Missing attributes on scaleway_tem_domain

### ISSUE THREAD

**Issue by Nainterceptor** [scaleway/terraform-provider-scaleway#1882]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a devOps engineer, I want to be able to hardcode the strict minimum of things, and automate the maximum of steps.
I have to, currently, hardcode SMTP host, username and port.
I have to, currently,  hardcode DKIM key (content is available).
I have to, currently, validate configuration step on console.
(Password will be fetch from IAM ressource creation)

### New or Affected Resource(s)

* scaleway_tem_domain

### Potential Terraform Configuration

No idea to pass steps, but host, username, ... can be added as attributes

### References

No

**Comment by quantumsheep** [comment]
Hello! I'm not sure to understand how you want to use the resource, can you give me an example?

About the validation step we have #1733 which will be handled soon.

Currently you should be able to create your infrastructure like this:
```hcl

resource "scaleway_tem_domain" "main" {
  name       = "example.com"
  accept_tos = true
}

resource "scaleway_domain_record" "dkim" {
  dns_zone = scaleway_tem_domain.main.name
  name     = "dkim._domainkey"
  type     = "TXT"
  data     = scaleway_tem_domain.main.dkim_config
  ttl      = 3600
}

resource "scaleway_domain_record" "spf" {
  dns_zone = scaleway_tem_domain.main.name
  name     = "@"
  type     = "TXT"
  data     = "v=spf1 ${scaleway_tem_domain.main.spf_config} -all"
  ttl      = 3600
}

resource "scaleway_domain_record" "mx" {
  dns_zone = scaleway_tem_domain.main.name
  name     = "@"
  type     = "MX"
  data     = "."
  ttl      = 3600
  priority = 0
}
```

**Comment by Nainterceptor** [comment]
Hi, that's ok to create resources, but then what ?
I want to inject tem information into CI/CD variables, or kubernetes secrets, or something else to let an application send email via tem.

In the following snippet, I want to get information, basically going to `gitlab_project_variable` from scaleway resources

```hcl
resource "scaleway_tem_domain" "main" {
  accept_tos = true
  name       = var.base_domain
}

// Like your example but via cloudflare it's working too 👍
resource "cloudflare_record" "dkim" {
  zone_id = lookup(data.cloudflare_zones.base_domain.zones[0], "id")
  // @todo: Use value from resource (https://github.com/scaleway/terraform-provider-scaleway/issues/1882)
  name  = "<redacted>._domainkey"
  value = scaleway_tem_domain.main.dkim_config
  type  = "TXT"
}

resource "cloudflare_record" "spf" {
  zone_id = lookup(data.cloudflare_zones.base_domain.zones[0], "id")
  name    = "@"
  value   = "v=spf1 ${scaleway_tem_domain.main.spf_config} -all"
  type    = "TXT"
}

resource "gitlab_project_variable" "smtp_host" {
  // @todo: Use value from resource (https://github.com/scaleway/terraform-provider-scaleway/issues/1882)
  key   = "SMTP_HOST"
  value = "smtp.tem.scw.cloud"
}

resource "gitlab_project_variable" "smtp_auth_user" {
  // @todo: Use value from resource (https://github.com/scaleway/terraform-provider-scaleway/issues/1882)
  key   = "SMTP_AUTH_USER"
  value = "<redacted>"
}

data "scaleway_account_project" "default" {
  name = "default"
}

resource "scaleway_iam_application" "main" {
  name  = "main(${var.base_domain})"
}

resource "scaleway_iam_api_key" "main" {
  application_id = scaleway_iam_application.main.id
  description    = "[Terraform] API key to send emails via transactional API"
}

resource "scaleway_iam_policy" "transac_email" {
  name           = "Email sending policy for ${var.base_domain}"
  description    = "[Terraform] Allow to send email"
  application_id = scaleway_iam_application.main.id
  rule {
    project_ids          = [data.scaleway_account_project.default.id]
    permission_set_names = ["TransactionalEmailEmailFullAccess"]
  }
}

resource "gitlab_project_variable" "smtp_auth_password" {
  key   = "SMTP_AUTH_PASSWORD"
  value = scaleway_iam_api_key.main.secret_key
}

resource "gitlab_project_variable" "smtp_port" {
  key = "SMTP_PORT"
  // @todo: Use value from resource (https://github.com/scaleway/terraform-provider-scaleway/issues/1882)
  value = "465"
}

resource "gitlab_project_variable" "smtp_tls" {
  key   = "SMTP_TLS"
  value = "true"
}
```

**Comment by adontz** [comment]
Not sure if I have to report this as a separate issue, but bot terraform provider and SCW cli currently return

    Error: scaleway-sdk-go: http error 501 Not Implemented: unknown service
    
when trying to create a tem domain

**Comment by quantumsheep** [comment]
@adontz Hey! Sorry for the delay. I suggest you update the CLI and the terraform provider and try again

**Comment by adontz** [comment]
> @adontz Hey! Sorry for the delay. I suggest you update the CLI and the terraform provider and try again

Actually it was because region was nl-ams and not fr-par. Error message could be less misleading I guess.
