### ISSUE TITLE
Whitespace in Redis ACLs are not sanitised 

### ISSUE THREAD

**Issue by ch9hn** [scaleway/terraform-provider-scaleway#1899]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_redis_cluster

### Terraform Configuration Files

```
      acls = [
        {
          ip          = " xxx.xxx.105.0/25" # <--- 1 whitespace
          description = "my ip"
        }

      ]
```

### Debug Output

` Error: expected "acl.2.ip" to be a valid IPv4 Value, got  xxx.xxx.105.0/25: invalid CIDR address:  xxx.xxx.105.0/25`

### Expected Behavior
Scaleway Terraform Plugin sanitised whitespace 

### Actual Behavior

Error that the CIDR is not valid.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Monitob** [comment]
Hello @ch9hn , this is part of the schema validation, otherwise this will provoke an undesirable update in place 
```  # scaleway_redis_cluster.main will be updated in-place
  ~ resource "scaleway_redis_cluster" "main" {
        id           = "fr-par-1/xxxx-xxxx-xxxx-xxx"
        name         = "test_redis_acl"
        # (10 unchanged attributes hidden)

      - acl {
          - description = "An acl description" -> null
          - id          = "xxxx-xxxx-xxxx-xxx"-> null
          - ip          = "0.0.0.0/0" -> null
        }
      + acl {
          + description = "An acl description"
          + id          = (known after apply)
          + ip          = " 0.0.0.0/0"
        }

        # (2 unchanged blocks hidden)
    }
```

**Comment by ch9hn** [comment]
Hello,
as mentioned in my original post - a CIDR with whitespace is not considered as valid CIDR.
After the post from @Monitob I understand why this is the case.
