### ISSUE TITLE
Getting information about an existing Project by name is not working

### ISSUE THREAD

**Issue by mehdicopter** [scaleway/terraform-provider-scaleway#1908]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```sh
Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/scaleway/scaleway v2.17.0
```

### Affected Resource(s)

* scaleway_account_project

### Terraform Configuration Files

```hcl
data scaleway_account_project "default" {
  name = "default"
  organization_id = "xxxx-xxx-xxxx-xxxx"
}
```

### Expected Behavior

According to the [documentation](<https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/account_project>), this should retrieve information about an existing Project.

### Actual Behavior

```sh
terraform plan
data.scaleway_account_project.default: Reading...

Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: scaleway-sdk-go: field ProjectID cannot be empty in request
│
│   with data.scaleway_account_project.default,
│   on data.tf line 2, in data "scaleway_account_project" "default":
│    2: data scaleway_account_project "default" {
│
╵
╷
│ Error: failed to read account project
│
│   with data.scaleway_account_project.default,
│   on data.tf line 2, in data "scaleway_account_project" "default":
│    2: data scaleway_account_project "default" {
│
```
### Steps to Reproduce

1. `terraform plan`

**Comment by Codelax** [comment]
Hi, thanks you for reporting this issue. There seems to be error checking issues.
Make sure that the api key you use come from the same organization as your project.
