### ISSUE TITLE
bug(secret): Error on null project_id

### ISSUE THREAD

**Issue by benoit-garcia** [scaleway/terraform-provider-scaleway#1916]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```shell
$ terraform version
Terraform v1.4.6
on darwin_arm64
+ provider registry.terraform.io/scaleway/scaleway v2.17.0
```

### Affected Resource(s)

* scaleway_secret

### Terraform Configuration Files

```hcl
## Define versions
terraform {
  required_version = ">= 0.13"
  required_providers {
    scaleway = {
      source  = "scaleway/scaleway"
      version = ">= 2.17.0"
    }
  }
}

## Configure providers
provider "scaleway" {
}

## Define variables
variable "project_id" {
  description = "ID of the project containing the secret. Ressource will be created in the project set at the provider level if null."
  type        = string
  default     = null
}

resource "scaleway_secret" "this" {
  name = "test-secret"

  description = "Test to create a secret setting a NULL project_id."
  project_id  = var.project_id
  tags = [
    "test",
    "debug"
  ]
}
```

### Expected Behavior

As `project_id` is optional, Terraform should provision the secret in a default project.

### Actual Behavior

Terraform throws an error; plan doesn't run at all.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by Codelax** [comment]
Hello, thanks for your interest with the provider.
In the provider documentation you can find the list of [required arguments](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs#arguments-reference).
The `project_id` field is optional for the secret resource as it can be defaulted using provider configuration. If both resource's `project_id` and provider's `project_id` are omitted, the creation will fail.

Don't hesitate to respond or open a new issue if you still have a problem
