### ISSUE TITLE
IAM: Changing application of an API key is allowed in TF but have no effect

### ISSUE THREAD

**Issue by boomaker** [scaleway/terraform-provider-scaleway#2021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.5.0 (same with older versions)

### Affected Resource(s)

* scaleway_iam_api_key

### Terraform Configuration Files

```hcl
# Create IAM application for global S3 access:
resource "scaleway_iam_application" "app" {
  name = "My App"
}

# Create API key to access bucket:
resource "scaleway_iam_api_key" "s3" {
  application_id = scaleway_iam_application.app.id
  description    = "Access to S3 buckets"
}
```

### Debug Output

If for whatever reason I need to change the application_id of the API Key:

Plan:
```
  # scaleway_iam_api_key.s3 will be updated in-place
  ~ resource "scaleway_iam_api_key" "s3" {
      ~ application_id     = "********" -> "***************"
        id                 = "SCW***************"
        # (8 unchanged attributes hidden)
    }
```

Apply:
```
scaleway_iam_api_key.s3: Modifying... [id=SCW*******]
scaleway_iam_api_key.s3: Modifications complete after 1s [id=SCW********]
```

### Expected Behavior

application_id of the API key is effectively changed server-side and API key is now affected to the new application.

### Actual Behavior

API key is still linked to the old application_id, and the next terraform plan will trigger again the change request.

### Important Factoids

PLEASE allow changing the application_id with an in-place update and NOT with a delete/recreate that would break the applications using the API key.

**Comment by boomaker** [comment]
> PLEASE allow changing the application_id with an in-place update and NOT with a delete/recreate that would break the applications using the API key.

Looks like #2023 will force a recreate 😢

**Comment by Codelax** [comment]
Sadly, this is the only outcome here. An api key is bound to a principal (app, user) and it cannot change
