### ISSUE TITLE
Switch private_network output of scaleway_baremetal_server from set to list

### ISSUE THREAD

**Issue by n-Arno** [scaleway/terraform-provider-scaleway#2029]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the scaleway_baremetal_server resource, the private_network output is a set instead of a list, so, using the output with a zipmap require some more gymnastic.

### New or Affected Resource(s)

* scaleway_baremetal_server

### Potential Terraform Configuration

```hcl

# simple use of zipmap to get all ips, note the .0.address which work since ipv4 is a list.
output "cluster" {
  value = zipmap(scaleway_baremetal_server.cluster.*.name, scaleway_baremetal_server.cluster.*.ipv4.0.address)
}

# doing the same with private_network fails and need a conversion to list to get the first element.
output "vlan_ids" {
  value = zipmap(scaleway_baremetal_server.cluster.*.name, [ for pn in scaleway_baremetal_server.cluster.*.private_network: tolist(pn)[0].vlan ])
}
```

### Error message

```
Error: Invalid index
│
│   on outputs.tf line 6, in output "vlan_ids":
│    6:   value = zipmap(scaleway_baremetal_server.cluster.*.name, scaleway_baremetal_server.cluster.*.private_network.0.vlan)
│
│ Elements of a set are identified only by their value and don't have any separate index or key to select with, so it's only possible to perform operations across all elements of the set.
```

### References

None

**Comment by Codelax** [comment]
First, the attribute splat expression `cluster.*.name` is legacy and [not recommended](https://developer.hashicorp.com/terraform/language/expressions/splat#legacy-attribute-only-splat-expressions).

You can use 
```hcl
output "vlan_ids" {
  value = zipmap(scaleway_baremetal_server.cluster[*].name, scaleway_baremetal_server.cluster[*].private_network[*].vlan)
}
```
Result
```
vlan_ids = {
  "tf-bm-nervous-ellis" = tolist([
    1863,
    1883,
  ])
  "tf-bm-vigilant-beaver" = tolist([
    2268,
    1883,
  ])
}
```

If you consider that baremetal are linked to only one private network, you can get the only vlan_id using `flatten`
```hcl
output "vlan_ids" {
  value = zipmap(scaleway_baremetal_server.cluster[*].name, flatten(scaleway_baremetal_server.cluster[*].private_network[*].vlan))
}
```
Result
```
vlan_ids = {
  "tf-bm-nervous-ellis" = 1863
  "tf-bm-vigilant-beaver" = 2268
}
```

Now for why we use a set instead of a list.
Changing the order of private networks have no impact with the API.
Having a list type would mean the user should be able to change the order of its private networks.
If the API does not allow us to change the order then we use Set type.
