### ISSUE TITLE
RDB node_type update is failing

### ISSUE THREAD

**Issue by Monitob** [scaleway/terraform-provider-scaleway#2046]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

```hcl
resource "scaleway_rdb_instance" "savprogroupe_internal_postgres2" {
  name              = "name"
  node_type         = "db-dev-s"
  engine            = "PostgreSQL-12"
  is_ha_cluster     = false
  region            = "fr-par"
  tags              = ["terraform-managed", "postgres", "internal-access", "api-entry_db", "api-sales_db"]
  volume_type       = "bssd"
  volume_size_in_gb = 20
}
```

### Debug Output

`Error: scaleway-sdk-go: resource instance with ID **** is in a transient state: disk_full`

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by blt909** [comment]
@Monitob the issue was on a `node_type` change
