### ISSUE TITLE
Modify RDB private instance configuration transform it in public instance

### ISSUE THREAD

**Issue by Gwenael22** [scaleway/terraform-provider-scaleway#2057]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.3
terraform-provider-scaleway 2.24.0

### Affected Resource(s)

* scaleway_rdb_instance

### Terraform Configuration Files

first instanciate a RDB without ip_net field

```hcl
private_network {
    pn_id = data.terraform_remote_state.network.outputs.private_network_id
 }
```

then, add ip_net configuration and apply the modification

```hcl
private_network {
    pn_id = data.terraform_remote_state.network.outputs.private_network_id
    ip_net = "172.16.19.8/22"
 }
```

The bug is also present if if you modify the CIDR in ip_net section on a private instance created with an ip_net value

```hcl
private_network {
    pn_id = data.terraform_remote_state.network.outputs.private_network_id
    ip_net = "172.16.19.8/32"
 }
```

### Expected Behavior

The RDB  is modified with the requested private IP endpoint (ex: 172.16.19.8:5432)

### Actual Behavior

The RDB  is modified with a public IP endpoint (ex: 195.154.196.110:24007)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sebastienbaillet** [comment]
I have a similar (and, I think, related) problem:

If you create a public db (without private_network block), and after that, you change it to make it private by adding a private_network block, the DB keeps its public ip address in addition to obtaining its private ip.
