### ISSUE TITLE
Can't create `scaleway_object_bucket_policy` 

### ISSUE THREAD

**Issue by boredland** [scaleway/terraform-provider-scaleway#2061]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

```
Terraform v1.5.3
on linux_amd64
+ provider registry.terraform.io/cloudflare/cloudflare v4.10.0
+ provider registry.terraform.io/hashicorp/aws v5.8.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/integrations/github v5.30.1
+ provider registry.terraform.io/mongodb/mongodbatlas v1.10.0
+ provider registry.terraform.io/scaleway/scaleway v2.24.0
+ provider registry.terraform.io/umisora/stripe v1.3.6
+ provider registry.terraform.io/vercel/vercel v0.14.0
```

### Terraform Configuration Files

```hcl
resource "scaleway_object_bucket_policy" "read_all" {
  bucket = scaleway_object_bucket.images.id
  policy = jsonencode({
    Version = "2023-04-17",
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject",
        ]
        Principal = { SCW = "application_id:xxx" }
        Resource = [
          scaleway_object_bucket.images.name,
          "${scaleway_object_bucket.images.name}/*",
        ]
      },
    ]
  })
}
```

### Panic Output

```
Error: error putting SCW bucket policy: MalformedPolicy: Action does not apply to any resource(s) in statement status code: 400, request id: tx29df4b60fb3a4e9b87a1e-0064b9537a, host id: tx29df4b60fb3a4e9b87a1e-0064b9537a
with module.production.scaleway_object_bucket_policy.read_all
on modules/environment/s3.tf line 52, in resource "scaleway_object_bucket_policy" "read_all":
resource "scaleway_object_bucket_policy" "read_all" {
```

### Expected Behavior

the resource (policy) to be created for the given bucket name.

### Important Factoids

I don't want to set a principal, but struggle to find a correct setting for that. AWS suggests setting 

```
Principal = {
  type = "*"
  identifiers = ["*"]
}
```

which doesn't seem to be valid in the eyes of the scw api validation.

**Comment by Sh4d1** [comment]
Hello! Haven't tested yet, but does `scaleway_object_bucket.images.name` resolve to something? Shouldn't it be `scaleway_object_bucket.images.id` ?

**Comment by boredland** [comment]
Using `name` comes straight from the [docs](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/object_bucket_policy#example-usage). However iirc I tried using `id` with an error indicating I was wrong.

**Comment by Sh4d1** [comment]
@boredland does the example from the docs work for you?

**Comment by Sh4d1** [comment]
Hello! Okay my bad. If you only need GetObject, you only need to specify the `<bucket>/*` line in the resource, and not the `<bucket>` line. For instance:

```tf
resource "scaleway_object_bucket_policy" "read_all" {
  bucket = "aaaa"
  policy = jsonencode({
    Version = "2023-04-17",
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject"
        ]
        Principal = { SCW = "application_id:696fd5e4-533f-40f7-9b3b-248938292698" }
        Resource = [
          "aaaa/*"
        ]
      },
    ]
  })
}
```

This works for me

**Comment by boredland** [comment]
Ok, neat. Will try!

**Comment by boredland** [comment]
This seems to have "worked" while I broke tons of things along the way and we had multiple days of outage and effectively being locked out from our buckets.

this is what seems to have worked for our case:

```hcl
resource "scaleway_object_bucket_policy" "read_all" {
  bucket = scaleway_object_bucket.images.id
  policy = jsonencode({
    Version = "2023-04-17",
    Statement = [
      {
        Effect    = "Allow"
        Action    = ["s3:GetObject"]
        Principal = "*"
        Resource = [
          "${scaleway_object_bucket.images.name}/*",
        ]
      },
    ]
  })
}
```

Will do some more tests tho.

**Comment by seb-xc** [comment]
Oh geez, I hit the same issue. I tried to create new project and two buckets and application per bucket. From some reason Principal doesn't work and I lost access to bucket from UI as well. It seems like for buckets my user does't inherit organisation/group/project permissions (WTF) and I needed to set additional rule eg.

```
{
        Effect = "Allow"
        Action = [
          "s3:*"
        ]
        "Principal": {
          "SCW": "user_id:<uuid>",
        },
        Resource = [
          scaleway_object_bucket.homelab_backups[each.key].name,
          "${scaleway_object_bucket.homelab_backups[each.key].name}/*"
        ]
      },
```

This IAM implementation sucks (wtf scaleway, you had one job, copy AWS' IAM 1:1), coming back to wasabi. I wasted few hours here

**Comment by Sh4d1** [comment]
Hello @mis4s ! Indeed, maybe it's not pointed out enough [in the docs](https://www.scaleway.com/en/docs/storage/object/api-cli/combining-iam-and-object-storage/), but when you specify a Statement (on the new schema version `2023-04-17`) then all others actions are automatically denied:

![image](https://github.com/scaleway/terraform-provider-scaleway/assets/990310/a16cc93b-db40-4975-9214-6cbb2242972a)

In that case it's needed to allow all other applications/users that need to access this bucket (including via the console). 

We are thinking about introducing a new schema version, which will try to address this issue! (Without having to allow all users that have IAM access on the bucket).

I'll also close this issue as the main problem is fixed.

**Comment by mis4s** [comment]
Ok, @Sh4d1 fair enough with this deny policy but even with additional principals my application keys could not access the bucket so one thing is the deny policy on organization level, and second the problem with access application keys to bucket.

**Comment by Sh4d1** [comment]
> but even with additional principals my application keys could not access the bucket so one thing is the deny policy on organization level

Hum not sure I get what you want to say, did you allow all your application IDs in a statement that allows everything?

> and second the problem with access application keys to bucket.
Not sure I get you again :sweat_smile:

**Comment by Sh4d1** [comment]
Could you paste your whole TF config, so I can try to replicate on my side?

**Comment by mis4s** [comment]
Sure,

I tried few time to works so after few attempts I tried various options like adding ListBucket, it is problematic in AWS as well or changing Resource. 

```terraform
terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
      version = "2.26.0"
    }
  }
}

provider "scaleway" {
  # Configuration options
  organization_id = "uuid"
}


data scaleway_account_project "default" {
  name = "default"
}

resource "random_id" "homelab_backups_project" {
  prefix      = "homelab-backups-"
  byte_length = 3
}

resource "scaleway_account_project" "homelab_backups" {
  name = random_id.homelab_backups_project.hex
}

locals {
  homelab_backup_buckets = toset([
    "vyos",
  ])
}


resource "random_id" "homelab_backups" {
  for_each = local.homelab_backup_buckets

  prefix      = "homelab-backups-${each.key}-"
  byte_length = 3
}

resource "scaleway_object_bucket" "homelab_backups" {
  for_each   = local.homelab_backup_buckets
  project_id = scaleway_account_project.homelab_backups.id

  region = "fr-par"

  name = random_id.homelab_backups[each.key].hex
}

resource "scaleway_iam_application" "homelab_backups" {
  for_each   = local.homelab_backup_buckets

  name        = random_id.homelab_backups[each.key].hex
}

resource "scaleway_object_bucket_policy" "homelab_backups" {
  for_each   = local.homelab_backup_buckets

  bucket = scaleway_object_bucket.homelab_backups[each.key].name
  project_id = scaleway_account_project.homelab_backups.id
  region = scaleway_object_bucket.homelab_backups[each.key].region
  policy = jsonencode({
    Version = "2023-04-17",
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:AbortMultipartUpload",
          "s3:DeleteObject",
          "s3:GetObject",
          "s3:ListBucket",
          "s3:ListBucketMultipartUploads",
          "s3:ListMultipartUploadParts",
          "s3:PutObject",
        ]
        Principal = { SCW = "application_id:${scaleway_iam_application.homelab_backups[each.key].id}" }
        Resource = [
          scaleway_object_bucket.homelab_backups[each.key].name,
          "${scaleway_object_bucket.homelab_backups[each.key].name}/*"
        ]
      },

      {
        Effect = "Allow"
        Action = [
          "s3:*"
        ]
        "Principal": {
          "SCW": "user_id:uuid",
        },
        Resource = [
          scaleway_object_bucket.homelab_backups[each.key].name,
          "${scaleway_object_bucket.homelab_backups[each.key].name}/*"
        ]
      },
    ]
  })
}

```

Also I had commented this (probably didn't work): 


```terraform
resource scaleway_iam_policy "object_read_only" {
  for_each   = local.homelab_backup_buckets

  name = "my policy"
  description = "gives app readonly access to object storage in project"
  application_id = scaleway_iam_application.homelab_backups[each.key].id
  rule {
    project_ids = [scaleway_account_project.homelab_backups.id]
    permission_set_names = ["ObjectStorageReadOnly"]
  }
}

resource "scaleway_iam_policy" "homelab_backups" {
  for_each = local.homelab_backup_buckets

  name           = "app"
  application_id = scaleway_iam_application.homelab_backups[each.key].id
  rule {
    project_ids = [
      data.scaleway_account_project.default.id,
      data.scaleway_account_project.default.id,
    ]
    permission_set_names = [
      "ObjectStorageObjectsDelete",
      "ObjectStorageObjectsRead",
      "ObjectStorageObjectsWrite",
    ]
  }
}
```

**Comment by Sh4d1** [comment]
Thanks! So I tested on my end, if I replace `uuid` with my user ID, I get no `MalformedPolicy` at all. And with the 2 `scaleway_iam_policy` resources, if I create an API key on a application (**with the preferred project for S3 set to the project of the buckets**), it works without any issues

**Comment by kindermoumoute** [comment]
Using terraform "preferred project for S3" can be configured like this on API key:

```hcl
resource "scaleway_iam_api_key" "homelab_backups" {
  for_each   = local.homelab_backup_buckets

  application_id = scaleway_iam_application.homelab_backups[each.key].id
  default_project_id = scaleway_account_project.homelab_backups.id
}
```

**Comment by mis4s** [comment]
Ok, thank you for checking and sorry for my noob behaviour, I will check it again @Sh4d1 

@kindermoumoute thanks, will check
