### ISSUE TITLE
scaleway_redis_cluster keeps on updating private_network.service_ips when using IPAM

### ISSUE THREAD

**Issue by georgeboot** [scaleway/terraform-provider-scaleway#2072]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v1.5.2, provider 2.25.1

### Affected Resource(s)

* scaleway_redis_cluster

### Terraform Configuration Files

```hcl
resource "scaleway_vpc_private_network" "net1" {
  name     = "net1"
}

resource "scaleway_redis_cluster" "test" {
  name         = "test"
  version      = "7.0.5"
  node_type    = "RED1-MICRO"
  user_name    = "admin"
  password     = "admin"
  cluster_size = 1
  private_network {
    id = scaleway_vpc_private_network.net1.id
    # dont set service_ips so that ipam will be used
  }
}
```

### Expected Behavior

Terraform should provision a cluster and set the IP assigned by IPAM to the service_ips field. Or alternatively, set it to a different field.

### Actual Behavior
The cluster gets created. On the next terraform run, Terraform thinks the `service_ips` should be empty and thus will generate a changeset to remove the IP.

### Important Factoids
Tried using:
```hcl
  lifecycle {
    ignore_changes = [
      private_network.service_ips
    ]
  }
```

But I cant because `Block type "private_network" is represented by a set of objects, and set elements do not have addressable keys. To find elements matching specific criteria, use a "for" expression with an "if" clause.`.

**Comment by georgeboot** [comment]
@quantumsheep what is the preferred way of getting the generated redis IPs, so we can use that when deploying our apps using Terraform? It's now computed but isn't (AFAIK) immediately available after creating the cluster.

**Comment by quantumsheep** [comment]
@georgeboot in the meantime I guess you can use the [scaleway_redis_cluster datasource](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/data-sources/redis_cluster):
```hcl
resource "scaleway_vpc_private_network" "net1" {
  name     = "net1"
}

resource "scaleway_redis_cluster" "test" {
  name         = "test"
  version      = "7.0.5"
  node_type    = "RED1-MICRO"
  user_name    = "admin"
  password     = "admin"
  cluster_size = 1
  private_network {
    id = scaleway_vpc_private_network.net1.id
  }
}

data "scaleway_redis_cluster" "cluster" {
  id = scaleway_redis_cluster.test.id
}

// data.scaleway_redis_cluster.cluster.private_network.*.service_ips.*
```
