### ISSUE TITLE
Cannot destroy `scaleway_vpc_private_network`

### ISSUE THREAD

**Issue by thotel** [scaleway/terraform-provider-scaleway#2125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.5.7
on linux_amd64
+ provider registry.terraform.io/scaleway/scaleway v2.13.1
```

### Affected Resource(s)

* scaleway_vpc_private_network

### Terraform Configuration Files

```hcl
provider "scaleway" {
  profile = "myProfile"
}

resource "scaleway_vpc_private_network" "pn01" {
  name = "test-1"
}
```

### Debug Output

https://gist.github.com/thotel/c9246505c5c5d7cd5f720e7bf484ab57
https://gist.github.com/thotel/62ca875d1e528ae793c5f8d6756d4d4b

### Expected Behavior

VPC private network should be created and destroyed successfully.

### Actual Behavior

VPC private network is successfully created but not destroyed. See output below, and it is still active in scw console even if removed from terraform state.

```
scaleway_vpc_private_network.pn01: Destroying... [id=fr-par-2/240941f3-9890-46b5-b936-5e2925c40339]
scaleway_vpc_private_network.pn01: Destruction complete after 0s
│
│ Warning: scaleway-sdk-go: resource private_network with ID 240941f3-9890-46b5-b936-5e2925c40339 is not found
│ 
│ 
│
```

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

**Comment by Codelax** [comment]
Hello, you might want to update your terraform provider.
There was the addition of vpc alongside private networks that was supported in last version. [More infos](https://www.scaleway.com/en/docs/network/vpc/reference-content/vpc-migration/).

**Comment by thotel** [comment]
Sure, sorry I didn't think about it !
