### ISSUE TITLE
Support managing Secret Manager folders

### ISSUE THREAD

**Issue by ndrpnt** [scaleway/terraform-provider-scaleway#2136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support managing [folders](https://www.scaleway.com/en/developers/api/secret-manager/#path-folders-list-folders) in Scaleway's Secret Manager.

### New or Affected Resource(s)

`scaleway_secret_folder` resource and datasource

**Comment by Codelax** [comment]
Folder do not exist anymore as a separate resource.
`scaleway_secret` provides a `path` parameter to change secret's path
