### ISSUE TITLE
[IAM] Allow setting permission_sets_scope_type of a rule in a IAM Policy

### ISSUE THREAD

**Issue by mig4ng** [scaleway/terraform-provider-scaleway#2148]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow to set the `permission_sets_scope_type` of a rule in a IAM Policy.

E.g. I want to create a rule that is not bond to a specific project or list of projects. I want to create a rule that is applied to all existing project and all future projects (similar to the default `Group - Administrator` Policy that is available in IAM).

Bonus: Document how to do it and all the types in the documentation.

I know IAM is fairly new to Scaleway, but it is quite amazing already and being able to use all the available functionality via Terraform is a nice to have. Keep the amazing work ❤️ 

### New or Affected Resource(s)

* scaleway_iam_policy

**Comment by Codelax** [comment]
Hi, thanks for you interest with the terraform provider and sorry for the delay.
If you want to create a rule for all existing projects and all future projects you can create a rule tied to your organization.
An example:
```hcl
resource scaleway_iam_application "app" {
  name = "my app"
}
resource scaleway_iam_policy "object_read_only" {
  name = "my policy"
  description = "gives app readonly access to object storage in project"
  application_id = scaleway_iam_application.app.id
  rule {
    organization_id = scaleway_iam_application.app.organization_id
    permission_set_names = ["ObjectStorageReadOnly"]
  }
}
```
This is what is done on the console if you select "All current and future projects".
I've added this example to the `iam_policy` documentation thanks to your issue.

**Comment by mig4ng** [comment]
Thank you @Codelax. I eventually added the policy from the UI and imported it in Terraform and realised it. However, I forgot to update this issue. Thanks for the update and glad it is now in the docs examples.

Always happy to help.
Have a great day!
