### ISSUE TITLE
Change behavior from update to replace resource for user_data/cloud-init on scaleway_instance_server

### ISSUE THREAD

**Issue by clementgoclock** [scaleway/terraform-provider-scaleway#2158]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When we make a change in the **cloud-init/user_data** section of a scaleway instance (using scaleway_instance_server), it doesn't trigger a replacement but rather an update.
We should consider triggering a replacement since cloud-init is only used at instance init :D

### New or Affected Resource(s)

* scaleway_instance_server

### Potential Terraform Configuration

```hcl
resource "scaleway_instance_server" "example_vm" {
  name              = "example.vm.tld"
  image             = "ubuntu_bionic"
  type              = "DEV1-S"
  provider          = scaleway.example
  ip_id             = scaleway_instance_ip.ip.id
  security_group_id = scaleway_instance_security_group.example_vm-sg.id
  tags              = ["hello", "public"]
  user_data = {
    cloud-init = templatefile("./resources/example.tpl", {
      information = var.updated_value
    })
  }
}
```

**Comment by Codelax** [comment]
Changing cloud-init will not trigger replacement as cloud-init execution can be controlled while inside the server.
Server replacement can be triggered using an intermediate resource and a lifecycle rule:
```hcl
resource "null_resource" "cloud-init" {
  triggers = {
    cloud-init-file = "#!/bin/sh\ntouch /file1"
  }
}

resource "scaleway_instance_ip" "ip" {}

resource "scaleway_instance_server" "server" {
  type = "PRO2-XXS"
  image = "ubuntu_jammy"
  ip_id = scaleway_instance_ip.ip.id

  user_data = {
    cloud-init = null_resource.cloud-init.triggers.cloud-init-file
  }

  lifecycle {
    replace_triggered_by = [
      null_resource.cloud-init.id
    ]
  }
}
```
