### ISSUE TITLE
Issue creating k8s cluster with 2.31.0

### ISSUE THREAD

**Issue by rfrerebe-stx** [scaleway/terraform-provider-scaleway#2187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_2.31.0

### Terraform Configuration Files

I declare a basic k8s cluster

```hcl
resource "scaleway_k8s_cluster" "k8s_cluster" {
  name                        = var.env_name
  description                 = "Env ${var.env_name} cluster"
  version                     = var.k8s_version
  cni                         = var.k8s_cni
  delete_additional_resources = true
}

```

### Debug Output

```
scaleway-sdk-go: invalid argument(s): private_network_id does not respect constraint, a Private Network is mandatory for this cluster type
```

### Expected Behavior

K8s cluster should be created

### Actual Behavior

K8s cluster creation fails

### Steps to Reproduce

1. `terraform apply` on a basic cluster

### Important Factoids

[documention](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_cluster) indicates this fields is optional ...
![image](https://github.com/scaleway/terraform-provider-scaleway/assets/77391972/1f1dfbbe-1542-48b5-b2f3-2db2b43ce021)

### References

There were no issue in 2.28.0

**Comment by remyleone** [comment]
Hello

You need to create a private network and pass the argument to the cluster. Private networks are now mandatory for kapsule clusters.

**Comment by rfrerebe-stx** [comment]
No problem, but the doc needs to be updated.
