### ISSUE TITLE
Provide IoT Hub MQTT CA

### ISSUE THREAD

**Issue by kipe** [scaleway/terraform-provider-scaleway#2264]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I've been setting up a test environment for IoT Hub, and have managed to get so far that the only thing I'm required to download via web UI is the MQTT networks CA file. I at least can't find a way to get it via the `scaleway_iot_hub` or `scaleway_iot_device` -objects.

### New or Affected Resource(s)

* scaleway_iot_hub
* scaleway_iot_device

### Potential Terraform Configuration

How I'd see it as working would be something like this:
```hcl
resource "scaleway_iot_hub" "iot-hub" {
  name = "iot-hub"
  product_plan = "plan_shared"
}

resource "local_sensitive_file" "iot-hub-ca" {
  filename = "${path.root}/iot-hub-ca.pem"
  content = scaleway_iot_hub.iot-hub.mqtt-ca
  directory_permission = 0700
  file_permission = 0400
}
```

Another option would be to add it to the device-certificates, but as it's not device-specific that doesn't seem like the correct place.

**Comment by Codelax** [comment]
Hi,
The `scaleway_iot_device` has a `certificate` block with 2 fields:
- `crt` is an optional input to set manually a certificate for the device, otherwise it will be generated by the API
- `key` is an exported field containing the private key in case the `crt` was generated by the API

You should be able to access the certificate using `scaleway_iot_device.my_device.certificate[0].crt`.

Both are documented in the [provider's documentation](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/iot_device)

**Comment by kipe** [comment]
Hi,
yes, the _device_ certificate is there, but to MQTT servers CA certificate cannot be found.

**Comment by Codelax** [comment]
The Certificate Authority download link is unique for the region, if you copy the link of the download button you should have a standard way of getting it.

**Comment by kipe** [comment]
@Codelax 
Thanks, I managed to work around it now by using
```hcl
# Download the certificate
# see: https://github.com/scaleway/terraform-provider-scaleway/issues/2264
data "http" "iot-hub-ca" {
  url = "https://iot.s3.nl-ams.scw.cloud/certificates/${scaleway_iot_hub.iot-hub.region}/iot-hub-ca.pem"
}
# Create configuration file for the IoT devices
resource "local_file" "iot-hub-ca" {
  filename = "${path.root}/iot-hub-ca.pem"
  content = data.http.iot-hub-ca.response_body
  directory_permission = 0700
  file_permission = 0400
}
```

It would be nicer to not have to use semi-hard-coded URLs, but this solution works quite ok :)

Leaving open for now, as at least I would prefer for the CA-file to be available through the `scaleway_iot_hub` -object.
