### ISSUE TITLE
RDB - Read Replica Multi-AZ error in ressource scaleway_rdb_instance (expected no more than 1 IP for instance, got 2)

### ISSUE THREAD

**Issue by nighoa** [scaleway/terraform-provider-scaleway#2399]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Teraform 1.5.7
Scaleway provider 2.37.0

### Affected Resource(s)

scaleway_rdb_instance with a scaleway_rdb_read_replica attachement

### Terraform Configuration Files

```hcl


## PAR-1 Zone

resource "scaleway_rdb_instance" "main" {
  name                      = "test-ha"
  node_type      = "DB-DEV-S"
  engine                    = "MySQL-8"
  is_ha_cluster             = true
  volume_type               = "bssd"

  private_network  {
      # The IP network address within the private subnet is determined by the IP Address Management (IPAM) service if not set.
      ip_net = null
      pn_id  = var.private_network.pn_id
      enable_ipam = true
  }
}

## PAR-2 Zone (supposed not the PAR-1 with same_zone = false) (maybe PAR-3 ?)

# Create a read_replica in another zone than the main instance
resource "scaleway_rdb_read_replica" "replica" {
  instance_id = scaleway_rdb_instance.main.id
  private_network {
    private_network_id = var.private_network.pn_id
    enable_ipam = true
  }
  same_zone = false
}
```

### Expected Behavior

works ;)

### Actual Behavior

│ Error: expected no more than 1 IP for instance, got 2
│   on ../../../../scw-tf-modules/rdb/main.tf line 1, in resource "scaleway_rdb_instance" "main":
│    1: resource "scaleway_rdb_instance" "main" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The read replica is setup correctly but the terraform apply never finish correctly.

![read-replica](https://github.com/scaleway/terraform-provider-scaleway/assets/25032867/a8304f11-70e8-470a-85ac-a10afc8d398c)

Seems that we have two IPs associate with the "ressource" (main and read_replica), provider seems lost.

### References

* #0000

**Comment by Mia-Cross** [comment]
Hi @nighoa, we've got several issues linked to this particular problem, a fix is on its way.
The error message is triggered when reading the resource, so creation should work as expected but reading and updating can't go through.
