### ISSUE TITLE
scaleway_secret_version datasource - Filters additions

### ISSUE THREAD

**Issue by jgalais** [scaleway/terraform-provider-scaleway#2655]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hello,

I use "scaleway_secret_version" data_source but some filters can be add to enhanced this datasource.

Filter addition proposal:
- revision = "latest"

It's an important thing because currently you must target the specific version.
If you want to split the secret version cycle and your Infrastructure as Code you can't do.

Can you add that on this resource too to have complete integration ?
i'am available if you have questions.

### New or Affected Resource(s)

* scaleway_secret_version (Data Source)

### Potential Terraform Configuration

```hcl
data "scaleway_secret_version" "application_admin_password" {
  project_id = "XXXXXXXX"
  revision   = "latest"
}
```

Thank you for your work.

Regards,

**Comment by jgalais** [comment]
Hello,

I edited my message to drop the path filter.
It was a poor understanding on my part because the path can be use on "scaleway_secret" data source.

Regards,

**Comment by Codelax** [comment]
Hi, as it is supported by the API, you should already be able to use `latest` in your revision filter.
I added its usage to our tests and it seems to work fine:
```
data "scaleway_secret_version" "data_by_name_latest" {
  secret_name = scaleway_secret.main.name
  revision    = "latest"
}
```

Thanks for reporting this, I also added a bit more info to the documentation

**Comment by jgalais** [comment]
Hello,

Thank you for your work.
