### ISSUE TITLE
secret manager: multiple elements found with the name my-secret

### ISSUE THREAD

**Issue by YoannBuch** [scaleway/terraform-provider-scaleway#2699]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.9.4
on linux_amd64
+ provider registry.terraform.io/scaleway/scaleway v2.43.0

```

### Affected Resource(s)

* scaleway_secret_version (**data source**)

### Terraform Configuration Files

Prerequisite : 

* Create secret "my-secret" in project A
* Create secret "my-secret" in project B

```hcl

data "scaleway_secret_version" "my_secret" {
  secret_name = "my-secret"
  revision    = "latest"
}

```

Providing explicitely the project_id argument does not fix anything.

### Debug Output

```
Error: multiple elements found with the name my-secret
```

### Panic Output

N/A

### Expected Behavior

Secret version can be read no matter how many times the secret name is reused across projects.

### Actual Behavior

Secret version cannot be read because the same secret name is reused across projects.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by Codelax** [comment]
Data source search across all your projects and it cannot guess which one it should choose.
If you want to use a specific project, you should be able to filter:
```hcl
data "scaleway_account_project" "my_project" {
  name = "My project"
}

data "scaleway_secret_version" "my_secret" {
  secret_name = "my-secret"
  revision    = "latest"
  project_id = data.scaleway_account_project.my_project.id
}
```

**Comment by YoannBuch** [comment]
Thanks! Will give it a try :)
