### ISSUE TITLE
scaleway_documentdb_private_network_endpoint state issue

### ISSUE THREAD

**Issue by D0wn3r** [scaleway/terraform-provider-scaleway#2712]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v1.9.4
on linux_amd64
+ provider registry.terraform.io/scaleway/scaleway v2.42.1
```

### Affected Resource(s)

* scaleway_documentdb_private_network_endpoint
* scaleway_rdb_instance

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
      version = "2.42.1"
    }
  }
  required_version = ">= 1.1.0"
}

provider "scaleway" {
  project_id        = "replaceme"
  zone            = "fr-par-2"
  region          = "fr-par"
  access_key      = "replaceme"
  secret_key      = "replaceme"
}

resource "scaleway_vpc_private_network" "vpc" {
  name = "test"
  ipv4_subnet {
      subnet = "192.168.0.0/24"
    }
}

resource "scaleway_rdb_instance" "postgresql" {
  name           = "test"
  node_type      = "DB-DEV-S"
  engine         = "PostgreSQL-15"
  is_ha_cluster  = false
  user_name      = "test"
  password       = "Th1s_is_my_password"
}

resource "scaleway_documentdb_private_network_endpoint" "main" {
  instance_id    = scaleway_rdb_instance.postgresql.id
  private_network {
    id           = scaleway_vpc_private_network.vpc.id
    ip_net       = "192.168.0.42/30"
  }
  depends_on = [scaleway_rdb_instance.postgresql]
}
```

### Debug Output

The output of terraform after the second apply with no modification:
https://gist.github.com/D0wn3r/fbdfcd31436bc17f525d90f85544f35e

### Expected Behavior

The private network should stay in the database if it doesn't have any modification

### Actual Behavior

When we apply even touching nothing, the private network is delete
First apply create everything ok
Second apply delete the private network from the database
Third apply will add again the private network to the database
...

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`
3. `terraform apply`

**Comment by remyleone** [comment]
I'm might be confused but why are you using a documentdb endpoint with an rdb endpoint? Those are two different products and I would think that their endpoint would be incompatible

**Comment by D0wn3r** [comment]
in the past (version: 2.42.1), I was able to specify a private ip on my psql db like this:
```
resource "scaleway_rdb_instance" "postgresql" {
  name           = var.database.name
  node_type      = var.database.node_type
  engine         = var.database.engine
  is_ha_cluster  = var.database.is_ha_cluster
  volume_type    = var.database.volume_type
  volume_size_in_gb = var.database.volume_size
  disable_backup = true
  user_name      = var.database.username
  password       = var.database.password
}

resource "scaleway_documentdb_private_network_endpoint" "main" {
  instance_id    = scaleway_rdb_instance.postgresql.id
  private_network {
    id           = scaleway_vpc_private_network.vpc.id
    ip_net       = var.database.ip_net
  }
  depends_on = [scaleway_rdb_instance.postgresql]
}
```

**Comment by D0wn3r** [comment]
It still works in 2.45 but not after @remyleone

**Comment by D0wn3r** [comment]
Sorry I was talking about another ticket (https://github.com/scaleway/terraform-provider-scaleway/issues/2801) at same time but yeah I just want to do a db with private ip

**Comment by remyleone** [comment]
Have you seen the documentation here: https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/rdb_instance#examples-of-endpoint-configuration

Documentdb will be discontinued/deprecated. I would strongly advocate for removing any usage of documentdb endpoint from your code.

**Comment by D0wn3r** [comment]
Any news about this @remyleone ? I would like to use 2.47.0 to have the fix of this too https://github.com/scaleway/terraform-provider-scaleway/pull/2745

**Comment by jremy42** [comment]
Yes, this replaces your previous configuration, and the issue should be fixed and release

**Comment by D0wn3r** [comment]
it works thank you
