### ISSUE TITLE
Uniform lb_beta to upstream api

### ISSUE THREAD

**Issue by alekc** [scaleway/terraform-provider-scaleway#418]
Current implementation of `lb_beta` has several important properties missing, such as 

- ip_id (which can cause issues with implementation of certificates)
- tags
- type (not sure about this one, docs are scarse on api page)
- ssl_compatibility_level (can be implemented only if https://github.com/scaleway/scaleway-sdk-go/issues/342 is done in go-sdk

we should add them.

**Comment by QuentinBrosse** [comment]
Hi,

What is the exact issue with `ip_id` please?

FYI, the scaleway/scaleway-sdk-go#342 has been merged, so this issue is not blocked anymore.

**Comment by alekc** [comment]
The issue with certificates. Atm, we cannot specify the ip_id for the load balancer, so its being assigned automatically. If a customer manages his dns records through the same terraform stack it's not an issue because he can do following chain: `LB->DNS Record->Certificate with common name resolving to lb'id`. 

However, if they do not manage the dns, then certificate creation will fail until they set a proper dns record. 

If it was possible precreate ip, and prepare dns records beforehand, then they could create lb and certificates in one go.
