### ISSUE TITLE
Feat (LB): implement alert subscribers for load balancer

### ISSUE THREAD

**Issue by alekc** [scaleway/terraform-provider-scaleway#424]
Atm we are missing entirely alerting part on the tf stack (https://developers.scaleway.com/en/products/lb/api/#alert-subscribers-5fc0b4)

I think this is a good candidate to be added to next release (1.15?)

**Comment by QuentinBrosse** [comment]
Good idea, we need to create a new `scaleway_lb_subscriber_beta`.

We can think about a schema together in this issue if you want. :)

**Comment by alekc** [comment]
sure, sounds good

**Comment by alekc** [comment]
@QuentinBrosse ended up doing most of the job while commuting today. What do you think of the current schema? I think the link between subscriber and lb should be on the lb side (as in this lb has following subscribers), but I am open to suggestions :)

**Comment by alekc** [comment]
@QuentinBrosse ping

**Comment by QuentinBrosse** [comment]
@alekc Sorry for the delay, I made a review of your PR. 👍

**Comment by remyleone** [comment]
After talking with @agirot, this feature won't be maintained in the v2 version of the load-balancer API. Therefore, the best option is to close it.
