### ISSUE TITLE
Add guide for configuring terraform backend with managed scaleway solution (S3, DBaaS)

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#483]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to have a guide that explains how to migrate a new state or an existing state to a managed backend such as Database as a service or an S3.

### References

- https://www.terraform.io/docs/backends/types/pg.html
- https://www.terraform.io/docs/backends/types/s3.html

**Comment by dirsigler** [comment]
In my opinion this is not a specific Scaleway "problem", but it still can be some kind of nice to have documentation to improve the experience of engineers starting things out and scaling their projects with Scaleways infrastructure.

Do you still need any help in this direction @remyleone ?
If yes, I would love to help you (and other engineers) out and maybe prepare some kind of example "growth" of a project. Concluding some instructions on how you transfer a local Terraform state into a S3 or PG compatible Scaleway solution.
