### ISSUE TITLE
Object Storage has no URL attribute

### ISSUE THREAD

**Issue by Hades32** [scaleway/terraform-provider-scaleway#495]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I want to use a created `scaleway_object_bucket` directly on some other resources (as the target of a backup process), but it seems I have to "guess" the URL myself. There should be an `endpoint` or `URL` attribute.

**Comment by remyleone** [comment]
It should land on our upcoming v2 release :)
