### ISSUE TITLE
Add lifecycle rules management for scaleway_object_bucket

### ISSUE THREAD

**Issue by achaussier** [scaleway/terraform-provider-scaleway#507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add lifecycle rules management for `scaleway_object_bucket` resource.

### New or Affected Resource(s)

* scaleway_object_bucket

### Potential Terraform Configuration

```hcl
...
lifecycle_rules = [
    {
        status = "enabled"
        name = "foobar"
        ...
    }
]
...
```

### References

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#using-object-lifecycle 
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/bucket.go#L269-L375
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/bucket.go#L2206-L2363
- https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/s3/bucket.go#L1139-L1266

**Comment by jerome-quere** [comment]
Relates to #506

**Comment by Owpac** [comment]
Hi! I think it could be a great feature to add and I also have this need.
But I'm a little worried since it's a 1 year old issue. Is there any news about it? :)

**Comment by Monitob** [comment]
Hi @Owpac we are gonna take care of this on the next release
