### ISSUE TITLE
New release including ingress=traefik2

### ISSUE THREAD

**Issue by daemonfire300** [scaleway/terraform-provider-scaleway#527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of writing this the PR for adding `traefik2` support landed in master. Is there any plan to do a minor release to include this in the provider?

### New or Affected Resource(s)

`resource_k8s_cluster_beta.go`

* scaleway__k8s_cluster_beta

### Potential Terraform Configuration

None

### References

- https://github.com/scaleway/terraform-provider-scaleway/commit/7caf1a986b98abee44956c3461f45498fd73c967

**Comment by vincentfretin** [comment]
In #573 I tested to deploy ingress traefik2 with provider scaleway 1.17, it worked.

**Comment by vincentfretin** [comment]
@remyleone You can close this one I think.

**Comment by Sh4d1** [comment]
Yes Traefik 2 is included in https://github.com/scaleway/terraform-provider-scaleway/releases/tag/v1.17.0 closing :smile:

**Comment by chinochao** [comment]
Is ingress available in 2.0.0?

**Comment by Sh4d1** [comment]
No, see #798 :)
