### ISSUE TITLE
Improve testing infrastructure (local and nightly acceptance tests)

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#559]
We would need 2 kind of process:

- A nightly process that will for real instantiate real resources, try to import pre-existing ones and check data sources. This nightly test suite could be run weekly or daily on a given organization.

- A local test suite that could use something similar as the VCR setup we use for testing interactions with the CLI. It would allow us to have a fast test suite able to run integration tests quickly without having to run tests on real infrastructure that take a long time to run.

**Comment by Monitob** [comment]
This two test has been implemented.
