### ISSUE TITLE
Latest version not on Terraform registry

### ISSUE THREAD

**Issue by nikaro** [scaleway/terraform-provider-scaleway#590]
Hello,

Just to say that https://registry.terraform.io/providers/scaleway/scaleway/latest still show the version 1.16.0 despite 1.17.0 is out since 10 days.

Is it normal ?

**Comment by Sh4d1** [comment]
Hello @nikaro ! Yes we are aware and this will probably be fixed beginning of next week ! 😄
I'll keep the issue opened until it's released !

**Comment by kerberjg** [comment]
Seems fixed now

**Comment by Sh4d1** [comment]
Yep 1.17.0 is out on the registry, I'll close!
