### ISSUE TITLE
Improve organization/project documentation

### ISSUE THREAD

**Issue by QuentinBrosse** [scaleway/terraform-provider-scaleway#606]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I think it should be interesting to add a paragraph in [the documentation home page](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs) to precise that at least an `organization_id` or a `project_id` should be filled for each resource. It's not possible to strongly type it (too much way to fill and override these fields) but a new paragraph can improve the comprehension for our users.

**Comment by chhein** [comment]
With only the organisation_id in my selected project scope i get the error message: 
`Error: scaleway-sdk-go: insufficient permissions: `
In this case the project_id is needed to fit the permissions for the scoped API credentials.

**Comment by remyleone** [comment]
`organization_id` is now computed (https://github.com/scaleway/terraform-provider-scaleway/pull/746) so project-id should be the only value used.
