### ISSUE TITLE
Add inline description for all fields

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#632]
Each field in a schema admits a Description field that can be used for documentation purposes https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html#support-for-resource-level-and-field-level-descriptions 

We could generate one file or several files using generators to use the content created for the SDK and the CLI and pass it here.

In particular, if those variables are generated it allows us to detect if a field is not implemented in the provider.

**Comment by Monitob** [comment]
The field description has been set on all the schema.Resources. Maybe you want to create a new issue to the generator purpose.
