### ISSUE TITLE
scaleway_instance_server private ip changes after modifications that imply a forced reboot

### ISSUE THREAD

**Issue by rcaillon-Iliad** [scaleway/terraform-provider-scaleway#659]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.13.5
+ provider registry.terraform.io/scaleway/scaleway v1.17.0
```

### Affected Resource(s)

* scaleway_instance_server

#### File 1 (first apply)

```hcl
resource "scaleway_instance_server" "test" {
  type = "DEV1-S"
  image = "ubuntu_focal"
  cloud_init = "foo"
}

resource "scaleway_instance_security_group" "test" {
  name = "foo"

  inbound_rule {
    action = "accept"
    ip = scaleway_instance_server.test.private_ip
  }
}
```
#### File 2 (second apply)

```hcl
resource "scaleway_instance_server" "test" {
  type = "DEV1-S"
  image = "ubuntu_focal"
  cloud_init = "bar"
}

resource "scaleway_instance_security_group" "test" {
  name = "bar"

  inbound_rule {
    action = "accept"
    ip = scaleway_instance_server.test.private_ip
  }
}
```

### Actual Behavior

The instance is stopped, then started again. This leads to a modification of the private IP associated to the instance. In my own use case, it breaks my server to server communications which use config files containing IP addresses.

Terraform also complains about this IP change:

```
Error: Provider produced inconsistent final plan

When expanding the plan for scaleway_instance_security_group.test to include
new values learned so far during apply, provider
"registry.terraform.io/scaleway/scaleway" produced an invalid new value for
.inbound_rule[0].ip: was cty.StringVal("10.65.30.139"), but now
cty.StringVal("10.64.62.179").

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

1. `terraform apply` (file 1)
2. `terraform apply` (file 2)

**Comment by vincentfretin** [comment]
related issues about private ip change: #573 and #529
Like @Sh4d1 said on slack, the provider currently stop/start that can trigger a new private ip assignment instead of a reboot apparently.

**Comment by Sh4d1** [comment]
Yeah, we should reboot when it's enough, not stop start 😄
