### ISSUE TITLE
Default value for "proxy_protocol" is incorrect when not defined ("proxy_protocol_proxy_protocol_none")

### ISSUE THREAD

**Issue by Raphux** [scaleway/terraform-provider-scaleway#692]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/local v2.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.0
+ provider registry.terraform.io/scaleway/scaleway v1.17.0

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

* scaleway_lb_backend_beta

### Terraform Configuration Files

```hcl
resource "scaleway_lb_backend_beta" "loadbalancer_redis_backend" {
  lb_id             = scaleway_lb_beta.loadbalancer_redis_base.id
  name              = "redis_backend"
  forward_protocol  = "tcp"
  forward_port      = "6379"
  server_ips        = scaleway_instance_server.elk-redis.*.private_ip
}
```

### Debug Output

https://gist.github.com/Raphux/036e398ae71d4e778ead1b373c293d52

### Expected Behavior

I guess defauft value for "proxy_protocol" should be "none", not "proxy_protocol_none".

### Actual Behavior

sdk validation failed with «unknown value "proxy_protocol_proxy_protocol_none"»

### Steps to Reproduce

Create a scaleway_lb_backend_beta with no "proxy_protocol" parameters.

**Comment by Sh4d1** [comment]
Already fixed by https://github.com/scaleway/terraform-provider-scaleway/pull/676 :)

**Comment by Raphux** [comment]
My bad, didn't find that one ! Thank you.

**Comment by Sh4d1** [comment]
@Raphux though the fix will only land in the next release, which will be the v2 along with some breaking changes I think 😅
