### ISSUE TITLE
Ensure that importing a server from a snapshot work

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#706]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

```hcl
# Copy-paste the minimal (if possible) terraform configuration to reproduce the bug here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by sokoow** [comment]
+1 here - is there any way of snapshotting and creating own OS images using scaleway provider yet ?

**Comment by remyleone** [comment]
Not at the moment, but you can create an image in the console and then import it using data resources. Note that [Packer](https://www.packer.io/docs/builders/scaleway) is also available for this exact purpose.

**Comment by sokoow** [comment]
ah, I didn't realize there's packer plugin for scaleway, that should do thanks

**Comment by Codelax** [comment]
For the moment we can create an image from a snapshot from console and then create an instance using this image
```hcl
resource "scaleway_instance_server" "server" {
  type = "DEV1-S"
  image = "aee3429c-8182-4e0d-95ac-73e37c5a42f4"
  ip_id = scaleway_instance_ip.public_ip.id 
}
```
Image cannot be created using terraform
A volume could be created using a snapshot, we can do it using terraform
```hcl
resource "scaleway_instance_volume" "server_volume" {
    type       = "l_ssd"
    name       = "some-volume-name"
    from_snapshot_id = "7692d6c5-fd7b-4b40-b4cc-b99741cdd9fb"
}
```
What is missing is creating an instance server using this volume as root volume, it is not available on scaleway console but it can be done using API

Example request to do so:
```
http https://api.scaleway.com/instance/v1/zones/fr-par-1/servers X-Auth-Token:"$SCW_SECRET_KEY" project="${SCW_DEFAULT_PROJECT_ID}" name=testserver commercial_type=DEV1-S volumes:='{"0":{"id":"29172f06-b9bb-490e-9937-07507e713943", "name":"volumeName", "boot": true}}'
```

**Comment by Codelax** [comment]
I created issues about root_volume, implementing it would allow importing a server from a snapshot
- #1303 
- #1304 

This could be done like this

```hcl
resource "scaleway_instance_volume" "server_volume" {
    type       = "l_ssd"
    name       = "some-volume-name"
    from_snapshot_id = "7692d6c5-fd7b-4b40-b4cc-b99741cdd9fb"
}
resource "scaleway_instance_server" "server" {
  type = "DEV1-S"
  image = "aee3429c-8182-4e0d-95ac-73e37c5a42f4"
  ip_id = scaleway_instance_ip.public_ip.id 
  root_volume {
    boot = true
    volume_id = scaleway_.instance_volume.server_volume.id
  }
}
```
