### ISSUE TITLE
Project ID support

### ISSUE THREAD

**Issue by tbalthazar** [scaleway/terraform-provider-scaleway#729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I use the [project feature](https://www.scaleway.com/en/docs/scaleway-project/) in the Scaleway Console, but AFAICT it's not supported in the Terraform provider yet:
```
$ terraform plan -out staging.plan

Error: Unsupported argument

  on main.tf line 13, in provider "scaleway":
  13:   project_id = "<my-project-id>"

An argument named "project_id" is not expected here.
```

It looks like support was added in this PR: https://github.com/scaleway/terraform-provider-scaleway/pull/601

Will a release supporting Project IDs be cut soon?

Thanks!

### Potential Terraform Configuration

```hcl
terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
      version = "1.17.2"
    }
  }
}

provider "scaleway" {
  zone   = var.zone
  region = var.region
  project_id = "<my-project-id>"
}
```

**Comment by Sh4d1** [comment]
@tbalthazar next release should be 2.0 -> https://github.com/scaleway/terraform-provider-scaleway/issues/576 
@remyleone any ETA on the release?

**Comment by QuentinBrosse** [comment]
For now, you can put your project ID in the `organization_id` field, it should work.

**Comment by Controlor** [comment]
Indeed it work, but it's a bit confusing. 
For example i created creds for my projects and have a lot of 403, since i was using the organisation id for the field `organisation_id`

**Comment by QuentinBrosse** [comment]
@Controlor you are right, it's confusing. That's why a project_id field will be added in the next release, as @Sh4d1 said above.

**Comment by Controlor** [comment]
Nice :) 

Any plan to have a ressource for creating the project from terraform?

**Comment by QuentinBrosse** [comment]
@Controlor we don't have a projects management public API today. But we think about it for the future yes. :)

**Comment by remyleone** [comment]
Project id is now supported in terraform. Additional support for project creation will be added when IAM will be released to the public.
