### ISSUE TITLE
Creating baremetal resources with 1.17.2

### ISSUE THREAD

**Issue by jeantil** [scaleway/terraform-provider-scaleway#739]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
> terraform -v                                                                                                                                                                                               
2021/01/06 17:49:07 [INFO] Terraform version: 0.14.3  
2021/01/06 17:49:07 [INFO] Go runtime version: go1.15.2
2021/01/06 17:49:07 [INFO] CLI args: []string{"/usr/bin/terraform", "-v"}
2021/01/06 17:49:07 [DEBUG] Attempting to open CLI config file: /home/jean/.terraformrc
2021/01/06 17:49:07 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory /home/jean/.terraform.d/plugins
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory /home/jean/.local/share/terraform/plugins
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory /usr/share/ubuntu/terraform/plugins
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory /usr/local/share/terraform/plugins
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory /usr/share/terraform/plugins
2021/01/06 17:49:07 [DEBUG] ignoring non-existing provider search directory /var/lib/snapd/desktop/terraform/plugins
2021/01/06 17:49:07 [INFO] CLI command args: []string{"version", "-v"}
Terraform v0.14.3
+ provider registry.terraform.io/kreuzwerker/docker v2.9.0
+ provider registry.terraform.io/scaleway/scaleway v1.17.2
+ provider registry.terraform.io/terraform-providers/docker v2.7.2
+ provider registry.terraform.io/terraform-providers/scaleway v1.17.2

```

### Affected Resource(s)

* scaleway_baremetal_server

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    docker = {
      source = "kreuzwerker/docker"
    }
    scaleway = {
      source = "scaleway/scaleway"
      version = "1.17.2"
    }
  }
}

provider "scaleway" {  
  zone            = "fr-par-2"
  region          = "fr-par"
  organization_id = "with the project id here"
}

resource "scaleway_baremetal_server" "baremetal" {
  zone        = "fr-par-2"
  offer       = "7fde3890-9787-488c-ac89-c4e00a4e5f83"  
  ssh_key_ids = ["with one of my ssh secret key uuid here"]  
  os           = "f2aeab5d-6015-4b7c-b4ed-d76e89093621"    
  hostname    = "baremetal" 
}

```
using the project id in organization id was from https://github.com/scaleway/terraform-provider-scaleway/issues/729#issuecomment-743776810

### Debug Output

https://gist.github.com/jeantil/4d9da1e5e254153de37f8379db8eee75

### Expected Behavior

* given a working `scw-cli` setup  (logged in and configured with a secret token)
* given the above terraform file filled with an appropriate project id and secret key
* I expect `terraform apply` to suceed and create a barmetal server with the requested OS in the configured project
* I expect `scw baremetal list` to list the newly created server.

### Actual Behavior

* given a working `scw-cli` setup  (logged in and configured with a secret token)
* given the above terraform file filled with an appropriate project id and secret key
* terraform apply fails with 
```
021-01-06T17:37:30.031+0100 [DEBUG] plugin.terraform-provider-scaleway_v1.17.2: 2021/01/06 17:37:30 [DEBUG] [DEBUG] POST https://api.scaleway.com/baremetal/v1/zones/fr-par-2/servers
2021-01-06T17:37:30.240+0100 [DEBUG] plugin.terraform-provider-scaleway_v1.17.2: 2021/01/06 17:37:30 [DEBUG] [DEBUG] POST https://api.scaleway.com/baremetal/v1/zones/fr-par-2/servers (status: 500): retrying in 2s (3 left)
2021-01-06T17:37:32.422+0100 [DEBUG] plugin.terraform-provider-scaleway_v1.17.2: 2021/01/06 17:37:32 [DEBUG] [DEBUG] POST https://api.scaleway.com/baremetal/v1/zones/fr-par-2/servers (status: 500): retrying in 4s (2 left)
2021-01-06T17:37:36.578+0100 [DEBUG] plugin.terraform-provider-scaleway_v1.17.2: 2021/01/06 17:37:36 [DEBUG] [DEBUG] POST https://api.scaleway.com/baremetal/v1/zones/fr-par-2/servers (status: 500): retrying in 8s (1 left)
scaleway_baremetal_server.baremetal: Still creating... [10s elapsed]
2021/01/06 17:37:44 [DEBUG] scaleway_baremetal_server.baremetal: apply errored, but we're indicating that via the Error pointer rather than returning it: scaleway-sdk-go: error executing request: POST https://api.scaleway.com/baremetal/v1/zones/fr-par-2/servers giving up after 4 attempts

Error: scaleway-sdk-go: error executing request: POST https://api.scaleway.com/baremetal/v1/zones/fr-par-2/servers giving up after 4 attempts

  on main.tf line 19, in resource "scaleway_baremetal_server" "baremetal":
  19: resource "scaleway_baremetal_server" "baremetal" {


```
* `scw baremetal list` shows that no server has been created

### Steps to Reproduce

1. `terraform apply`
2. `scw baremetal list`

**Comment by remyleone** [comment]
@jeantil Hello, 👋  I was not able to reproduce this error from your code. The retry seems to be a network problem or some error on the API side. Feel free to reach me on [Slack](https://slack.scaleway.com/) with your organization id so we can look it up.

**Comment by jeantil** [comment]
for readers who encounter this until v2.0.0 is available, the conclusion is that 
- v1.17.2 doesn't support project ids 
- baremetal api doesn't support using a project id in place of the organisation id
- v2.0.0-rc is expected to be published real soon, alternatively one can compile the provider from source on master and put it in the provider folder of his tf project.
