### ISSUE TITLE
scaleway_account_ssh_key issue with loop

### ISSUE THREAD

**Issue by Kamaradeivanov** [scaleway/terraform-provider-scaleway#755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.4

### Affected Resource(s)

provider registry.terraform.io/scaleway/scaleway v1.17.2

### Terraform Configuration Files

```hcl
variable "users" {
  description = "Create users with these names"
  type        = list(object({ name=string, sshkey=string }))
  default     = [
    {
      "name": "test1",
      "sshkey": "ssh-rsa  XXXXXXXXXXXXXXXXXXXXXXX",
    },
    {
      "name": "test2",
      "sshkey": "ssh-rsa  XXXXXXXXXXXXXXXXXXXXXXX",
    }
  ]
}

terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
      version = "1.17.2"
    }
  }
  required_version = ">= 0.14"
}

provider "scaleway" {
  region          = "fr-par"
  zone            = "fr-par-1"
}

resource "scaleway_account_ssh_key" "ssh_key" {
  count = length(var.users)
  name = var.users[count.index].name
  public_key = var.users[count.index].sshkey
}

output "all_keys" {
  value       = scaleway_account_ssh_key.ssh_key[*].id
  description = "All users informations"
}
```

### Debug Output

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

Outputs:

all_keys = [
  "fe879a54-ab6c-4a26-a4ac-21596671e0f2",
  "fe879a54-ab6c-4a26-a4ac-21596671e0f2",
]

### Expected Behavior

I should have different id and multiple entries in my scaleway console

### Actual Behavior

I only have one entry named test2 (the last one of my list) in my scaleway console.
Ouput always have same ids.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`

**Comment by remyleone** [comment]
I cannot reproduce. Are you sure the variable passed in the users contain the right information? I've put two different keys in the users and the key appears in my console with your snippet.

**Comment by Kamaradeivanov** [comment]
Indeed, my bad.
I used the same key twice for my test, but it's apparently not relevent ^^.
