### ISSUE TITLE
scaleway_k8s_cluster issue with api error

### ISSUE THREAD

**Issue by mkazinauskas** [scaleway/terraform-provider-scaleway#763]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.4

### Affected Resource(s)

+ provider registry.terraform.io/scaleway/scaleway v2.0.0-rc1

scaleway_k8s_cluster
scaleway_k8s_pool

### Terraform Configuration Files

resource "scaleway_k8s_cluster" "test" {
  name             = "test"
  description      = "test cluster"
  version          = "1.20.2"
  cni              = "cilium"
  enable_dashboard = true
  ingress          = "nginx"
}

resource "scaleway_k8s_pool" "test" {
  cluster_id  = scaleway_k8s_cluster.test.id
  name        = "test"
  node_type   = "DEV1-M"
  size        = 1
  autoscaling = false
  autohealing = true
  min_size    = 1
  max_size    = 1
}

### Debug Output

Error: scaleway-sdk-go: error executing request: Post "https://api.scaleway.com/k8s/v1/regions/pl-waw/clusters": POST https://api.scaleway.com/k8s/v1/regions/pl-waw/clusters giving up after 4 attempt(s)

### Expected Behavior

Kubernetes cluster had to be created

### Actual Behavior

Error: scaleway-sdk-go: error executing request: Post "https://api.scaleway.com/k8s/v1/regions/pl-waw/clusters": POST https://api.scaleway.com/k8s/v1/regions/pl-waw/clusters giving up after 4 attempt(s)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by Sh4d1** [comment]
Hey! Kapsule is not available in waw yet, but soon :)

**Comment by mkazinauskas** [comment]
My bad. :)

**Comment by Sh4d1** [comment]
@mkazinauskas it is now 😉

**Comment by chinochao** [comment]
Is ingress available in  scaleway_k8s_cluster 2.0.0?
