### ISSUE TITLE
Error: missing expected { - Regression from commit c89b594

### ISSUE THREAD

**Issue by hydezhao** [scaleway/terraform-provider-scaleway#764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.14.4

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl
# Copy-paste the minimal (if possible) terraform configuration to reproduce the bug here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

terraform plan works.

### Actual Behavior

```
❯ terraform plan   

Error: missing expected {
```

### Steps to Reproduce
with a minimum tf file 
```hcl
provider "scaleway" {}

resource "scaleway_instance_server" "test" {
  type  = "GP1-XS"
  image = "df78ce76-d926-44f1-80ab-ecc4e8e05f66"
  name  = "test"
}
```

1. Compile plugin with version ( commit 6d9a5f45 )
2. terraform init && terraform plan && terraform apply -> OK
3. Compile plugin with version ( commit c89b594 )
4. terraform plan KO with `Error: missing expected {`

**Comment by hydezhao** [comment]
It might be related to the breaking change of user_data.
with commit 6d9a5f4, `user_data` is created in tfstate like this
```
            "user_data": [
              
            ],
```
with commit c89b594, `user_data` is created in tfstate like this:
```
            "user_data": null,
```

**Comment by hydezhao** [comment]
BTW there is a little missing on document:
https://github.com/scaleway/terraform-provider-scaleway/blame/master/docs/guides/migration_guide_v2.md#L208

a `=` is missing between `user_data` and `{`

**Comment by remyleone** [comment]
thanks for the documentation typo; The documentation was fixed to include the `=`  in 809072eb

**Comment by remyleone** [comment]
As for the cloud-init problem, it comes from a tfstate persistence model incompatibility. Luckily it can be fixed quite easily by removing the problematic resource from the state using `terraform state rm` and then importing it using `terraform import` with the id of the resource that you can find on scaleway.

You can also follow the migration guide https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/guides/migration_guide_v2#migration-guide-for-renamed-resources that provide similar instruction for migrating to a resource that changed its name.

**Comment by DavidOliver** [comment]
Thanks for the guidance. Here are the commands in full in case anyone else is looking for them.

```
$ terraform state rm scaleway_instance_server.my_server_name
$ terraform import scaleway_instance_server.my_server_name my_server_id
```

**Comment by DavidOliver** [comment]
After removing the server from the state, I'm finding that although the state import is described as successful my server doesn't seem to exist in the updated state.

`terraform plan` shows the server is to be created, and the server isn't listed in `terraform state list`.

```
$ terraform import scaleway_instance_server.web_phx_02 nl-ams-1/{instance_id}
scaleway_instance_server.web_phx_02: Importing from ID "nl-ams-1/{instance_id}"...
scaleway_instance_server.web_phx_02: Import prepared!
  Prepared scaleway_instance_server for import
scaleway_instance_server.web_phx_02: Refreshing state... [id=nl-ams-1/{instance_id}]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```

Any ideas? (I can delete the server, recreate and redeploy easily enough if need be.)

**Comment by DavidOliver** [comment]
Sorry, please ignore the above post. I think I managed to use the wrong ID. Having corrected that, the plan now shows a replacement rather than creation.

It's the "image" which "forces replacement": from "nl-ams-1/{UUID}" to "ubuntu_bionic". I haven't changed the image in the module code.

```
resource "scaleway_instance_server" "web_phx_02" {
  name              = "web-phx-02"
  image             = "ubuntu_bionic"
  type              = "STARDUST1-S"
  ip_id             = scaleway_instance_ip.web_phx_02_ip.id
  security_group_id = scaleway_instance_security_group.https.id
}
```

I guess I'll be redeploying after all. :)

**Comment by DavidOliver** [comment]
I've overwritten the 'image' value in the state file with 'ubuntu_bionic', and the plan now doesn't mention the instance server in question. This seems rather hacky, but I'll apply and see what happens!
