### ISSUE TITLE
Apple Silicon (M1) CPU support

### ISSUE THREAD

**Issue by imcitius** [scaleway/terraform-provider-scaleway#774]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hello,
Is support for `darwin_arm64` arch is planned?

Currently `terraform init` throws an error trying to init project:
```
citius@Ilyas-MacBook-Pro k8s-scaleway % terraform init   

Initializing the backend...

Initializing provider plugins...
- Finding latest version of scaleway/scaleway...

Error: Incompatible provider version

Provider registry.terraform.io/scaleway/scaleway v1.17.2 does not have a
package available for your current platform, darwin_arm64.

Provider releases are separate from Terraform CLI releases, so not all
providers are available for all platforms. Other versions of this provider may
have different platforms supported.
```

Thanks.

**Comment by remyleone** [comment]
https://github.com/scaleway/terraform-provider-scaleway/pull/776

**Comment by lyoko17220** [comment]
Hello, 

Do you have any idea when the darwin_arm64 version will be released on the official repository?

**Comment by remyleone** [comment]
In the upcoming v2 that is going to come up in the next weeks, if you are in a hurry, you can compile the provider and attach your terraform to it. https://www.terraform.io/docs/extend/debugging.html#starting-a-provider-in-debug-mode
