### ISSUE TITLE
Can't set a value for organization_id in provider configuration version 2.0.0

### ISSUE THREAD

**Issue by ArcRiiad** [scaleway/terraform-provider-scaleway#793]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* provider configuration

### Terraform Configuration Files

```hcl
provider "scaleway" {
  zone               = var.ZONE_OF_MY_SCALEWAY_PROJECT
  organization_id    = "ID_OF_MY_SCALEWAY_PROJECT"
  access_key         = var.MY_SCALEWAY_PROJECT_SCW_ACCESS_KEY
  secret_key         = var.MY_SCALEWAY_PROJECT_SCW_SECRET_KEY
}
```

### Debug Output

https://gist.github.com/ArcRiiad/d1fd1380eac5be95971b53419ef727ba

### Expected Behavior

The provider should accept this argument as it is described in the current documentation on Terraform (https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/guides/migration_guide_v2#provider-configuration)

Nota: the same configuration works well with the version 1.7

### Actual Behavior

The provider throw an error.

### Steps to Reproduce

1. Try to set an `organization_id` in the provider configuration.

2. `terraform apply`

**Comment by ArcRiiad** [comment]
By changing `organization_id` by `project_id` and using the same credentials,I'm facing this error

```
Error: scaleway-sdk-go: http error 403 Forbidden: authorization required
Error: couldn't read volume: scaleway-sdk-go: http error 403 Forbidden: authorization required
Error: scaleway-sdk-go: http error 403 Forbidden: authorization required
Error: couldn't read volume: scaleway-sdk-go: http error 403 Forbidden: authorization required
Error: scaleway-sdk-go: http error 403 Forbidden: authorization required
Error: couldn't read volume: scaleway-sdk-go: http error 403 Forbidden: authorization required
```

**Comment by labynocle** [comment]
I guess we can close this issue.

It seems that if in your env you set `SCW_ACCESS_KEY` and `SCW_SECRET_KEY` , then even if in your terraform code you have:

```
provider "scaleway" {
  zone               = var.ZONE_OF_MY_SCALEWAY_PROJECT
  organization_id    = "ID_OF_MY_SCALEWAY_PROJECT"
  access_key         = var.MY_SCALEWAY_PROJECT_SCW_ACCESS_KEY
  secret_key         = var.MY_SCALEWAY_PROJECT_SCW_SECRET_KEY
}
```

your `access_key` and `secret_key` will use `SCW_ACCESS_KEY` and `SCW_SECRET_KEY` instead of `var.MY_SCALEWAY_PROJECT_SCW_ACCESS_KEY` and `var.MY_SCALEWAY_PROJECT_SCW_SECRET_KEY`

by simply unset `SCW_ACCESS_KEY` and `SCW_SECRET_KEY`, `access_key` and `secret_key` fallback to `var.MY_SCALEWAY_PROJECT_SCW_ACCESS_KEY` and `var.MY_SCALEWAY_PROJECT_SCW_SECRET_KEY`

**Comment by remyleone** [comment]
Yes, this is a behavior of the SDK and it is on purpose. The goal is to be able to override variables from code with environment variables.  You can also define those variables in the scaleway config file https://github.com/scaleway/scaleway-sdk-go/tree/master/scw#config-file-path
