### ISSUE TITLE
InstanceServer Type for Stardust instances is not aligned with other instance TypeNames

### ISSUE THREAD

**Issue by dirsigler** [scaleway/terraform-provider-scaleway#794]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.14.7
+ provider registry.terraform.io/scaleway/scaleway v2.0.0-rc.2

### Affected Resource(s)

https://registry.terraform.io/providers/scaleway/scaleway/2.0.0-rc.2/docs/resources/instance_server#arguments-reference
https://www.scaleway.com/en/pricing/

* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_server" "bastion" {
  name  = "bastion-host"
  type  = "STARDUST1-S"
  image = "ubuntu_focal"

  tags = ["ssh", "mosh", "bastion"]

  ip_id       = scaleway_instance_ip.public_ip.id
  enable_ipv6 = true

  root_volume {
    # Disk Size of Stardust instances is limited to 10 GB - https://www.scaleway.com/en/stardust-instances/
    # For additional disk size you have to add a scaleway_instance_volume
    size_in_gb = 10
  }

  security_group_id = scaleway_instance_security_group.web.id
}
```

### Expected Behavior

The documentation states, that you have to look on the pricing page for the virtual_instance type "Name" to get the desired name to use for your Terraform configuration value. Which was true for the previous provider versions (1.17.2).

### Actual Behavior

If you now use the current name which is used on the pricing page to create your virtual_instance with the Stardust type, you have to use 
```hcl
[...]
  type  = "STARDUST1-S"
[...]
```

but the pricing page says "Stardust1-s"

PS: I am sorry for the really bad explanation and title. In the end it is just an issue about a typo or missing info in the documentation.

**Comment by relgisri** [comment]
Additionally: 
I just saw that the documentation is also [saved in the repository](https://github.com/scaleway/terraform-provider-scaleway/blob/v2.0.0-rc.2/docs/resources/instance_server.md).
So if you like I would open a PR
