### ISSUE TITLE
bucket creation sometime leads to error 400

### ISSUE THREAD

**Issue by fredleger** [scaleway/terraform-provider-scaleway#796]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform 0.13.3
provider version 1.17.2

### Affected Resource(s)

* scaleway_object_bucket

### Terraform Configuration Files

```hcl
resource "scaleway_object_bucket" "my-bucket" {
    name = "${var.base_name}-bucket"
    acl = "private"
    region = var.region
}
```

### Expected Behavior

Idempotent behavior

### Actual Behavior

```
Error: BadRequest: <html><h1>Bad Request</h1><p>The server could not comply with the request since it is either malformed or otherwise incorrect.</p></html>
status code: 400, request id: txcc41b22f31304c439daac-xxxxxxxxxx, host id: txcc41b22f31304c439daac-xxxxxxxxxx

on modules/backups-location/object-storage-bucket.tf line 1, in resource "scaleway_object_bucket" "backups-location":
1: resource "scaleway_object_bucket" "backups-location" {

"}
```
Only happens sometimes and his fixed by the second apply afterwards
But as we want to build it in an automated way this is quite an issue

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Called via a module but i don't see any possible impact here

**Comment by angristan** [comment]
This is not an issue with the provider, but an issue with the Object Storage internals itself, which we are aware of. We are working on fixing it (it happens randomly).
