### ISSUE TITLE
RDB Allowed Ips

### ISSUE THREAD

**Issue by chinochao** [scaleway/terraform-provider-scaleway#802]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* scaleway_rdb_instance

Can we have support for allowed IPs from Terraform?

https://www.scaleway.com/en/docs/database-instance/#-Configuring-Allowed-IPs

**Comment by jeansebastienh** [comment]
Hi @chinochao 

We have a PR open on this topic : https://github.com/scaleway/terraform-provider-scaleway/pull/784

I hope that we will publish this by end of the week.
