### ISSUE TITLE
Provider should display API POST content in debug mode

### ISSUE THREAD

**Issue by fredleger** [scaleway/terraform-provider-scaleway#809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When facing an error you might wan't to set `TF_LOG=TRACE` and check all the steps are behaving as expected to dig a bit further.
For now it seems that the provider does not include any useful infos except HTTP status code

Exemple:

```
2021-04-11T15:40:48.703+0200 [INFO]  plugin.terraform-provider-scaleway_v2.0.0: 2021/04/11 15:40:48 [DEBUG] [DEBUG] POST https://api.scaleway.com/instance/v1/zones/fr-par-2/servers (status: 500): retrying in 8s (1 left): timestamp=2021-04-11T15:40:48.703+0200
```

### New or Affected Resource(s)

None

### Potential Terraform Configuration

None

### References

None

**Comment by jeansebastienh** [comment]
Hi @fredleger 

What kind of information would you like to see in the output ?

Note: you can enable the debug information of the [sdk](https://github.com/scaleway/scaleway-sdk-go) by setting the following variable:
```bash
export SCW_DEBUG=1
```

**Comment by fredleger** [comment]
Hi @jeansebastienh,

I guess this was the information i was missing. thanks for pointing it to me.

/close
