### ISSUE TITLE
Trying to create the snapshot of scaleway instance using terraform. Can anyone help me with that?

### ISSUE THREAD

**Issue by sathwikadhikari** [scaleway/terraform-provider-scaleway#812]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* scaleway_XXXX

### Terraform Configuration Files

```hcl
# Copy-paste the minimal (if possible) terraform configuration to reproduce the bug here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by remyleone** [comment]
@sathwikadhikari working on it in https://github.com/scaleway/terraform-provider-scaleway/pull/815 :) feel free to test it and let us know what you think
