### ISSUE TITLE
Kubernetes API not yet ready when node pool creation complete

### ISSUE THREAD

**Issue by joaomlneto** [scaleway/terraform-provider-scaleway#818]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

---

### Description

When I create a cluster and a node pool using the [third example from the `scaleway_k8s_cluster` documentation ("with the kubernetes provider")](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_cluster#with-the-kubernetes-provider), if I immediately attempt to create a namespace, it results in an error.

### Terraform Version
`Terraform v0.15.0 on darwin_amd64`. Also reproducible on `v0.14.0`.

### Affected Resource(s)

* [`scaleway_k8s_cluster`](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_cluster)
* [`scaleway_k8s_pool`](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_pool)

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    scaleway = {
      source = "scaleway/scaleway"
      version = ">= 2.0.0"
    }
  }

  required_version = ">= 0.15"
}

provider "scaleway" {
  zone       = var.scaleway_zone
  region     = var.scaleway_region
  project_id = var.scaleway_project_id
  access_key = var.scaleway_access_key
  secret_key = var.scaleway_secret_key
}

provider "kubernetes" {
  host = null_resource.kubeconfig.triggers.host
  token = null_resource.kubeconfig.triggers.token
  cluster_ca_certificate = base64decode(null_resource.kubeconfig.triggers.cluster_ca_certificate)
}

resource "scaleway_k8s_cluster" "cluster" {
  name    = var.cluster_name
  version = var.cluster_version
  cni     = var.container_network_interface

  auto_upgrade {
    enable = true
    maintenance_window_start_hour = 1
    maintenance_window_day = "any"
  }
}

resource "scaleway_k8s_pool" "pool" {
  cluster_id  = scaleway_k8s_cluster.cluster.id
  name        = var.cluster_name
  node_type   = var.node_type
  size        = var.num_nodes
  min_size    = var.min_nodes
  max_size    = var.max_nodes
  autoscaling = true
  autohealing = true
}

resource "null_resource" "kubeconfig" {
  depends_on = [scaleway_k8s_pool.pool]
  triggers = {
    host                   = scaleway_k8s_cluster.cluster.kubeconfig[0].host
    token                  = scaleway_k8s_cluster.cluster.kubeconfig[0].token
    cluster_ca_certificate = scaleway_k8s_cluster.cluster.kubeconfig[0].cluster_ca_certificate
  }
}

resource "kubernetes_namespace" "user" {
  metadata {
    name = var.username
  }
}
```

### Actual Behavior

```hcl
kubernetes_namespace.user: Creating...

│ Error: Post "https://ffffffff-ffff-ffff-ffff-ffffffffffff.api.k8s.fr-par.scw.cloud:6443/api/v1/namespaces": EOF
│ 
│   on ../../modules/kubernetes-dev-namespace/namespace.tf line 1, in resource "kubernetes_namespace" "user":
│    1: resource "kubernetes_namespace" "user" {
```

### Steps to Reproduce

1. `terraform apply`

**Comment by jtherin** [comment]
Can you try to set [wait_for_pool_ready](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/k8s_pool#wait_for_pool_ready) ?

**Comment by joaomlneto** [comment]
😱 Shame on me for my blindness, but that indeed fixes it. Apologies for this non-bug report!
