### ISSUE TITLE
Default Ingress Controller - scaleway_k8s_cluster

### ISSUE THREAD

**Issue by allupaku** [scaleway/terraform-provider-scaleway#851]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hello, we would like to have support for default ingress controller via Scaleway_k8s_cluster, do you think that is in the pipeline soon ? 

Meanwhile will, how can we allocate ip addresses / range of ip addresses for our ingress resources ? Are we supposed to rely on loadbalancers for that ?

### New or Affected Resource(s)

* scaleway_k8s_cluster

### Potential Terraform Configuration

```hcl
resource "scaleway_k8s_cluster" "vh" {
...

ingress = "nginx"
}
```

### References

* #0000

**Comment by Sh4d1** [comment]
Hello! 
This field was present on previous TF versions, bit it is going to be deprecated in the API very soon, so we decided to exclude it from Terraform. 

Best way, imho, is helm with Terraform and to manage the ingress yourself! 

And if you want to manage the IP addresses through the ingress, you'll need a load balancer yes!
