### ISSUE TITLE
No way to attach instances to the VPC

### ISSUE THREAD

**Issue by dirsigler** [scaleway/terraform-provider-scaleway#861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```bash
terraform -v
Terraform v1.0.3
on darwin_amd64
+ provider registry.terraform.io/integrations/github v4.12.2
+ provider registry.terraform.io/scaleway/scaleway v2.1.0
```

### Affected Resource(s)

scaleway_instance_server
scaleway_vpc_private_network
scaleway_instance_private_nic

### Terraform Configuration Files

```hcl
resource "scaleway_vpc_private_network" "primary" {
  name = "my-vpc"
}

resource "scaleway_instance_ip" "public_ip" {}

resource "scaleway_instance_server" "dev_instance" {
  name               = var.virtual_instance_name
  type               = var.virtual_instance_type
  image              = var.virtual_instance_image
  tags               = var.common_tags
  ip_id              = scaleway_instance_ip.public_ip.id
  enable_ipv6        = true

  root_volume {
    size_in_gb = 10
  }
}
```

### Expected Behavior

I would expect to have an argument which I can provide to the "scaleway_instance_server" to attach it to my newly created VPC.
An existing example (which I tested out and didn't work) would be from [scaleway_instance_private_nic](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/instance_private_nic#private_network_id) **private_network_id**.

### Actual Behavior

The virtual server instance and VPC are created separately and therefore I have to manually attach the instance to my VPC.

### References

**Comment by remyleone** [comment]
Hello, could you try with a config file like this one: https://github.com/scaleway/terraform-provider-scaleway/blob/master/scaleway/resource_instance_private_nic_test.go#L29-L41 

```hcl
resource scaleway_vpc_private_network pn01 {
    name = "TestAccScalewayInstancePrivateNIC_Basic"
}

resource "scaleway_instance_server" "server01" {
    image = "ubuntu_focal"
    type  = "DEV1-S"
}

resource scaleway_instance_private_nic nic01 {
    server_id          = scaleway_instance_server.server01.id
    private_network_id = scaleway_vpc_private_network.pn01.id
}
```

**Comment by dirsigler** [comment]
This seems to work!
But I had to destroy my instance and recreate it again in combination with the new private_nic to make it work - which in my situation is fine.

Thank you!
