### ISSUE TITLE
Implement per resource timeout

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#924]
### Description

https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts

### New or Affected Resource(s)

All resources

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

- [x] #992
- [x] #993
- [x] #994
- [x] #995
- [x] #996
- [x] #997
- [x] #999
- [x] #998
- [x] #1000
- [x] #1001
- [x] #1002
- [x] #1003
- [x] #1004
- [x] #1005
- [x] #1007
- [x] #1006
- [x] #1008
- [x] #1009
- [x] #1010
- [x] #1011
- [x] #1012
- [x] #1013
- [x] #1014
- [x] #1015
- [x] #1016

**Comment by cebernard22** [comment]
this option would be very helpful, since destroy is not working today for gpu instances due to a timeout issue

**Comment by cbernard-psee** [comment]
This enhancement would be very helpful,  since  terraform destroy is not working today for gpu instances due to timeout issue

**Comment by remyleone** [comment]
@cbernard-psee could you try using the timeout block defined here: https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts We are using this version of the SDK so it should be able to override the default timeout.
