### ISSUE TITLE
Issue on switch public ip on instance_server

### ISSUE THREAD

**Issue by lde** [scaleway/terraform-provider-scaleway#969]
Hi,
I'm having an issue for switching in on an instance server.
No issue on attachment but only for switching.
I've checked Status immediately after detaching it seems be detached.
I've checked status immediately after attachment it seems be attached.
It appends about one of two trials.

I've fixed it by waiting few seconds after detaching an ip: in this fork of provider: [Repo](https://github.com/lde/terraform-provider-scaleway/tree/dirty_fix_detach) 

Here is a terraform stack where you can produce this behaviours by  changing `reverse_order` to true after an apply. [Repo](https://github.com/lde/sample_instance_scaleway)

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

terraform 1.0.11

### Affected Resource(s)

* scaleway_instance_server

### Terraform Configuration Files

```hcl
resource "scaleway_instance_ip" "eip" {
  count = local.number_of_instances
}

variable "reverse_order" {
  type = bool
  default = false
}

resource "scaleway_instance_server" "instance" {
  count = local.number_of_instances
  image = "56b594d3-7623-49a5-94ca-492c625cfa79"
  type  = "GP1-S"
  ip_id = local.ip_list[count.index]
}

locals {
  number_of_instances=2
  raw_ip_list=tolist(scaleway_instance_ip.eip.*.id)
  ip_list=var.reverse_order?reverse(local.raw_ip_list):local.raw_ip_list
}

terraform {
  required_providers {
    scaleway = {
      source="scaleway/scaleway"
    }
  }
}

provider "scaleway" {
  region = "fr-par"
  zone = "fr-par-2"
}

```

### Steps to Reproduce

1. `terraform apply`
2. `TF_VAR_reverse_order=true terraform apply`

### References

* #0000

**Comment by Monitob** [comment]
I'm not available to reproduce this bug before many fixes on the waiting process. Please feel free to open a new issue if this persists for you
